-- =====================================================================
-- PVCAR — 0001_baseline.sql
-- Schema inicial de la base nueva. Sin datos.
--
-- Origen: Backup_bd/prod_schema_public_2026-07-27.sql (35 tablas).
-- Curado a mano: se quitó el preámbulo de pg_dump, la propiedad de
-- objetos, los duplicados y el residuo del scaffold de Lovable.
--
-- Orden de ejecución: PVCAR_Dev primero. Solo si sale limpio, PVCAR.
-- Todo va en una transacción: si algo falla, no queda nada a medias.
--
-- Cada cambio respecto a la base vieja está marcado con [FIX].
-- Las decisiones que deliberadamente NO se tomaron aquí están al final,
-- en el bloque "PENDIENTE DE DECISIÓN".
-- =====================================================================

BEGIN;

-- =====================================================================
-- 1. TABLAS DE CATÁLOGO
--    Sin dependencias. Se poblan con 0004_seed_dev.sql en dev y con la
--    carga del cutover en prod.
-- =====================================================================

CREATE TABLE public.estado (
    est_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    est_nombre text NOT NULL
);

CREATE TABLE public.dia (
    dia_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dia_nombre text NOT NULL
);

CREATE TABLE public.asistencia_estado (
    asisest_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asisest_nombre text NOT NULL
);

CREATE TABLE public.categoria (
    cat_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cat_nombre text NOT NULL,
    cat_descripcion text
);

CREATE TABLE public.categoria_nino_grado (
    catninograd_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    catninograd_nombre text NOT NULL
);

CREATE TABLE public.encuesta_tipo_respuesta (
    encutiporesp_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    encutiporesp_nombre text NOT NULL
);

CREATE TABLE public.evaluacion_tipo_metodo (
    evatipometo_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evatipometo_nombre text NOT NULL
);

-- [FIX] En la base vieja rol usa GENERATED ALWAYS. Eso obliga a
-- OVERRIDING SYSTEM VALUE al cargar los datos del cutover, y es la única
-- tabla que se comporta distinto. Se unifica en BY DEFAULT.
CREATE TABLE public.rol (
    rol_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rol_nombre text NOT NULL,
    rol_titulo text NOT NULL,
    rol_descripcion text
);

-- =====================================================================
-- 2. USUARIOS Y PERMISOS
-- =====================================================================

-- [FIX] Tres cambios respecto a la base vieja:
--   1. Fuera usu_contrasena. Era text NOT NULL con las contraseñas en
--      claro. Las gestiona Supabase Auth (bcrypt).
--   2. auth_user_id: enlace con auth.users. Nullable porque los usuarios
--      inactivos no consumen cuenta en Auth hasta que se reactiven.
--      El CHECK obliga a que todo usuario activo (est_id = 1) la tenga.
--   3. usu_correo pierde el UNIQUE simple; se reemplaza por un índice
--      único sobre lower(trim(...)) más abajo. Supabase Auth normaliza el
--      correo a minúsculas: sin esto, 'Juan@x.com' y 'juan@x.com' son dos
--      usuarios distintos aquí y el mismo allá.
CREATE TABLE public.usuario (
    usu_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    auth_user_id uuid,
    usu_nombre text NOT NULL,
    usu_correo text NOT NULL,
    usu_foto text,
    usu_telefono text,
    usu_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    usu_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    est_id smallint DEFAULT '1'::smallint NOT NULL,
    CONSTRAINT usuario_activo_requiere_auth
        CHECK (est_id <> 1 OR auth_user_id IS NOT NULL)
);

COMMENT ON COLUMN public.usuario.auth_user_id IS
    'FK lógica a auth.users.id. La puebla db/scripts/backfill-auth.ts (Fase 5). '
    'No se declara FK real: auth.users es de Supabase y no se referencia desde public.';

CREATE TABLE public.usuario_rol (
    usurol_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usu_id integer NOT NULL,
    rol_id integer NOT NULL
);

CREATE TABLE public.rol_permiso (
    rolper_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rol_id integer NOT NULL,
    modulo text NOT NULL,
    accion text DEFAULT 'ver'::text NOT NULL
);

-- =====================================================================
-- 3. COLEGIOS, ACTIVIDADES Y HORARIOS
-- =====================================================================

CREATE TABLE public.colegio (
    col_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    col_nombre text NOT NULL,
    col_direccion text NOT NULL,
    col_rep_nombre text,
    col_rep_foto text,
    col_rep_telefono text,
    col_rep_email text,
    col_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    col_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.colegio_coordinador (
    colcoor_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    col_id integer NOT NULL,
    usu_id integer NOT NULL
);

CREATE TABLE public.actividad (
    act_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cat_id integer,
    act_nombre text NOT NULL,
    act_descripcion text,
    act_espacio_trabajo text,
    act_tipo_espacio text,
    act_espacio_secundario text,
    act_indumentaria_tipo text,
    act_materiales_alumno text[],
    act_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    act_fecha_modificacion timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.colegio_actividad_horario (
    colacthor_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    col_id integer,
    act_id integer,
    dia_id smallint,
    colacthor_hora_inicio time without time zone,
    colacthor_hora_fin time without time zone,
    est_id smallint DEFAULT '1'::smallint,
    colacthor_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL
);

-- =====================================================================
-- 4. ENTRENADORES
-- =====================================================================

CREATE TABLE public.entrenador (
    ent_id integer NOT NULL,
    ent_cedula text,
    ent_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ent_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    est_id smallint DEFAULT '1'::smallint NOT NULL
);

COMMENT ON TABLE public.entrenador IS
    'ent_id NO es autogenerado: es el mismo usu_id del usuario. '
    'Relación 1:1 con usuario, con FK ON DELETE CASCADE.';

CREATE TABLE public.entrenador_asignacion (
    entasig_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ent_id integer,
    colacthor_id integer,
    entasig_fecha_inicio date NOT NULL,
    entasig_fecha_fin date,
    est_id smallint DEFAULT '1'::smallint NOT NULL
);

CREATE TABLE public.entrenador_auxiliar (
    entaux_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usu_id integer,
    rol_id integer,
    est_id smallint DEFAULT '1'::smallint,
    ent_id integer
);

-- =====================================================================
-- 5. ESTUDIANTES Y PADRES
-- =====================================================================

CREATE TABLE public.nino (
    nino_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nino_nombre text NOT NULL,
    nino_foto text,
    nino_edad smallint,
    nino_cedula text,
    nino_toma_transporte boolean,
    nino_info_salud text,
    nino_otra_info text,
    nino_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    nino_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    col_id integer NOT NULL,
    catninograd_id smallint,
    est_id smallint DEFAULT '1'::smallint
);

CREATE TABLE public.nino_asignacion (
    ninoasig_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nino_id integer NOT NULL,
    colacthor_id integer NOT NULL,
    ninoasig_fecha_inscripcion timestamp with time zone DEFAULT now() NOT NULL,
    ninoasig_fecha_baja timestamp with time zone DEFAULT now(),
    est_id smallint
);

CREATE TABLE public.padre (
    padre_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    padre_sector_residencia text,
    padre_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    padre_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    usu_id integer
);

CREATE TABLE public.nino_padre (
    ninopadre_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nino_id integer,
    padre_id integer
);

-- =====================================================================
-- 6. ASISTENCIAS
-- =====================================================================

CREATE TABLE public.asistencia_nino (
    asisnino_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nino_id integer NOT NULL,
    asisest_id smallint NOT NULL,
    usu_registrador integer NOT NULL,
    asisnino_fecha date NOT NULL,
    asisnino_hora_tarde time without time zone DEFAULT now(),
    asisnino_razon_justificado text,
    asisnino_fecha_registrado timestamp with time zone DEFAULT now() NOT NULL,
    colacthor_id integer NOT NULL
);

CREATE TABLE public.asistencia_entrenador (
    asisent_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asisent_fecha date NOT NULL,
    ent_id integer NOT NULL,
    asisest_id smallint NOT NULL,
    asisent_hora_tarde time without time zone DEFAULT now(),
    usu_registrador integer NOT NULL,
    asisent_fecha_registrado timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    asisent_razon_justificado text,
    col_id integer NOT NULL
);

CREATE TABLE public.asistencia_auxiliar (
    asisaux_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asisaux_fecha date NOT NULL,
    usu_id integer NOT NULL,
    asisest_id smallint NOT NULL,
    asisaux_hora_tarde time without time zone DEFAULT now(),
    usu_registrador integer NOT NULL,
    asisaux_fecha_registrado timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    asisaux_razon_justificado text,
    col_id integer NOT NULL
);

-- =====================================================================
-- 7. EVALUACIONES
-- =====================================================================

CREATE TABLE public.evaluacion (
    eva_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    eva_creador integer NOT NULL,
    est_id smallint DEFAULT '1'::smallint NOT NULL,
    eva_titulo text NOT NULL,
    eva_descripcion text,
    eva_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    eva_categoria text,
    eva_puntaje_total numeric(10,2) DEFAULT 0
);

COMMENT ON COLUMN public.evaluacion.eva_puntaje_total IS
    'Derivada: la mantiene el trigger trigger_update_evaluacion_puntaje_total '
    'sumando evaluacion_parametro.evaparam_puntaje. No escribir a mano.';

CREATE TABLE public.evaluacion_asignacion (
    evaasig_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    eva_id integer NOT NULL,
    colacthor_id integer NOT NULL,
    est_id smallint DEFAULT '1'::smallint
);

-- [FIX] En la base vieja usa CREATE SEQUENCE + DEFAULT nextval (estilo
-- serial). Se unifica en identity como el resto de las tablas.
CREATE TABLE public.evaluacion_parametro (
    evaparam_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    eva_id integer NOT NULL,
    evaparam_nombre text NOT NULL,
    evaparam_nota text,
    evatipometo_id smallint,
    evaparam_intentos smallint,
    evaparam_escala_min smallint,
    evaparam_escala_max smallint,
    evaparam_puntaje smallint NOT NULL,
    CONSTRAINT evaluacion_parametro_evaparam_intentos_check
        CHECK ((evaparam_intentos >= 1))
);

COMMENT ON COLUMN public.evaluacion_parametro.evaparam_puntaje IS
    'Puntaje del parámetro asignado manualmente pero se divide en la cantidad de intentos';

-- [FIX] La base vieja tiene 9 constraints en esta tabla, de las cuales 3
-- están duplicadas literalmente:
--   check_different_times == evaluacion_tiempo_rangos_check1
--   check_max_op          == evaluacion_tiempo_rangos_evatieran_max_op_check
--   check_min_op          == evaluacion_tiempo_rangos_evatieran_min_op_check
-- Se conserva una de cada par. Quedan 6.
CREATE TABLE public.evaluacion_tiempo_rangos (
    evatieran_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evaparam_id integer NOT NULL,
    evatieran_op_cero text NOT NULL,
    evatieran_tiempo_cero integer NOT NULL,
    evatieran_op_full text NOT NULL,
    evatieran_tiempo_full integer NOT NULL,
    CONSTRAINT check_different_times
        CHECK ((evatieran_tiempo_cero <> evatieran_tiempo_full)),
    CONSTRAINT check_min_op
        CHECK ((evatieran_op_cero = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text]))),
    CONSTRAINT check_max_op
        CHECK ((evatieran_op_full = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text]))),
    CONSTRAINT check_min_tiempo_positive
        CHECK ((evatieran_tiempo_cero > 0)),
    CONSTRAINT check_max_tiempo_positive
        CHECK ((evatieran_tiempo_full > 0)),
    CONSTRAINT evaluacion_tiempo_rangos_check
        CHECK ((((evatieran_op_cero = ANY (ARRAY['<'::text, '<='::text]))
                 AND (evatieran_op_full = ANY (ARRAY['>'::text, '>='::text]))
                 AND (evatieran_tiempo_full > evatieran_tiempo_cero))
             OR ((evatieran_op_cero = ANY (ARRAY['>'::text, '>='::text]))
                 AND (evatieran_op_full = ANY (ARRAY['<'::text, '<='::text]))
                 AND (evatieran_tiempo_full < evatieran_tiempo_cero))))
);

CREATE TABLE public.evaluacion_nino_pendiente (
    evaninopen_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    eva_id integer,
    ninoasig_id integer NOT NULL,
    est_id smallint DEFAULT '6'::smallint NOT NULL,
    usu_id_registrador integer,
    evaninopen_fecha_finalizacion timestamp with time zone
);

CREATE TABLE public.evaluacion_intento (
    evaint_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    evaparam_id integer NOT NULL,
    evaint_intento smallint NOT NULL,
    evaint_tiempo integer,
    evaint_logro boolean,
    evaint_num smallint,
    evaninopen_id integer,
    evaint_mobak smallint,
    evaint_puntaje_obtenido real
);

-- =====================================================================
-- 8. ENCUESTAS
--    Nota: las 4 tablas de encuesta* tienen 0 filas en producción.
--    Se replican por paridad; su futuro se decide en la Fase 13.
-- =====================================================================

CREATE TABLE public.encuesta (
    encu_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    encu_titulo text NOT NULL,
    encu_descripcion text,
    encu_creador integer NOT NULL,
    est_id smallint NOT NULL,
    encu_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    encu_fecha_modificacion timestamp with time zone DEFAULT now()
);

CREATE TABLE public.encuesta_pregunta (
    encupreg_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    encu_id integer NOT NULL,
    encupreg_orden smallint NOT NULL,
    encupreg_pregunta text NOT NULL,
    encupreg_nota text,
    encutiporesp_id smallint NOT NULL,
    encupreg_escala_min smallint,
    encupreg_escala_max smallint
);

CREATE TABLE public.encuesta_respondida (
    encurespo_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    encu_id integer NOT NULL,
    padre_id integer NOT NULL,
    encurespo_fecha_registro timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.encuesta_respuesta (
    encurespu_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    encurespo_id integer NOT NULL,
    encupreg_id bigint NOT NULL,
    encurespu_texto text,
    encurespu_num numeric,
    encurespu_fecha timestamp with time zone,
    encurespu_hora time with time zone,
    encurespu_sino boolean
);

-- =====================================================================
-- 9. PRIMARY KEYS
-- =====================================================================

ALTER TABLE ONLY public.actividad
    ADD CONSTRAINT actividad_pkey PRIMARY KEY (act_id);
ALTER TABLE ONLY public.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_pkey PRIMARY KEY (asisaux_id);
ALTER TABLE ONLY public.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_pkey PRIMARY KEY (asisent_id);
ALTER TABLE ONLY public.asistencia_estado
    ADD CONSTRAINT asistencia_estado_pkey PRIMARY KEY (asisest_id);
ALTER TABLE ONLY public.asistencia_nino
    ADD CONSTRAINT asistencia_nino_pkey PRIMARY KEY (asisnino_id);
ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (cat_id);
ALTER TABLE ONLY public.categoria_nino_grado
    ADD CONSTRAINT categoria_nino_grado_pkey PRIMARY KEY (catninograd_id);
ALTER TABLE ONLY public.colegio
    ADD CONSTRAINT colegio_pkey PRIMARY KEY (col_id);
ALTER TABLE ONLY public.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_pkey PRIMARY KEY (colacthor_id);
ALTER TABLE ONLY public.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_pkey PRIMARY KEY (colcoor_id);
ALTER TABLE ONLY public.dia
    ADD CONSTRAINT dia_pkey PRIMARY KEY (dia_id);
ALTER TABLE ONLY public.encuesta
    ADD CONSTRAINT encuesta_pkey PRIMARY KEY (encu_id);
ALTER TABLE ONLY public.encuesta_pregunta
    ADD CONSTRAINT encuesta_pregunta_pkey PRIMARY KEY (encupreg_id);
ALTER TABLE ONLY public.encuesta_respondida
    ADD CONSTRAINT encuesta_respondida_pkey PRIMARY KEY (encurespo_id);
ALTER TABLE ONLY public.encuesta_respuesta
    ADD CONSTRAINT encuesta_respuesta_pkey PRIMARY KEY (encurespu_id);
ALTER TABLE ONLY public.encuesta_tipo_respuesta
    ADD CONSTRAINT encuesta_tipo_respuesta_pkey PRIMARY KEY (encutiporesp_id);
ALTER TABLE ONLY public.entrenador
    ADD CONSTRAINT entrenador_pkey PRIMARY KEY (ent_id);
ALTER TABLE ONLY public.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_pkey PRIMARY KEY (entasig_id);
ALTER TABLE ONLY public.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_pkey PRIMARY KEY (entaux_id);
ALTER TABLE ONLY public.estado
    ADD CONSTRAINT estado_pkey PRIMARY KEY (est_id);
ALTER TABLE ONLY public.evaluacion
    ADD CONSTRAINT evaluacion_pkey PRIMARY KEY (eva_id);
ALTER TABLE ONLY public.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_pkey PRIMARY KEY (evaasig_id);
ALTER TABLE ONLY public.evaluacion_intento
    ADD CONSTRAINT evaluacion_intento_pkey PRIMARY KEY (evaint_id);
ALTER TABLE ONLY public.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_pkey PRIMARY KEY (evaninopen_id);
ALTER TABLE ONLY public.evaluacion_parametro
    ADD CONSTRAINT evaluacion_parametro_pkey PRIMARY KEY (evaparam_id);
ALTER TABLE ONLY public.evaluacion_tiempo_rangos
    ADD CONSTRAINT evaluacion_tiempo_rangos_pkey PRIMARY KEY (evatieran_id);
ALTER TABLE ONLY public.evaluacion_tipo_metodo
    ADD CONSTRAINT evaluacion_tipo_metodo_pkey PRIMARY KEY (evatipometo_id);
ALTER TABLE ONLY public.nino
    ADD CONSTRAINT nino_pkey PRIMARY KEY (nino_id);
ALTER TABLE ONLY public.nino_asignacion
    ADD CONSTRAINT nino_asignacion_pkey PRIMARY KEY (ninoasig_id);
ALTER TABLE ONLY public.nino_padre
    ADD CONSTRAINT ninopadre_pkey PRIMARY KEY (ninopadre_id);
ALTER TABLE ONLY public.padre
    ADD CONSTRAINT padre_pkey PRIMARY KEY (padre_id);
ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (rol_id);
ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_pkey PRIMARY KEY (rolper_id);
ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (usu_id);
ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_pkey PRIMARY KEY (usurol_id);

-- =====================================================================
-- 10. UNIQUE CONSTRAINTS
-- =====================================================================

ALTER TABLE ONLY public.dia
    ADD CONSTRAINT dia_dia_nombre_key UNIQUE (dia_nombre);
ALTER TABLE ONLY public.estado
    ADD CONSTRAINT estado_est_nombre_key UNIQUE (est_nombre);
ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_rol_nombre_key UNIQUE (rol_nombre);
ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_rol_id_modulo_accion_key UNIQUE (rol_id, modulo, accion);
ALTER TABLE ONLY public.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_unique UNIQUE (col_id, usu_id);
ALTER TABLE ONLY public.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_eva_colacthor_unique UNIQUE (eva_id, colacthor_id);
ALTER TABLE ONLY public.nino_padre
    ADD CONSTRAINT ninopadre_nino_id_padre_id_key UNIQUE (nino_id, padre_id);

-- [FIX] La base vieja tiene DOS unique sobre evaluacion_tiempo_rangos
-- (evaparam_id): evaluacion_tiempo_rangos_evaparam_id_key y
-- unique_evaparam_id. Son el mismo índice pagado dos veces. Queda uno.
ALTER TABLE ONLY public.evaluacion_tiempo_rangos
    ADD CONSTRAINT evaluacion_tiempo_rangos_evaparam_id_key UNIQUE (evaparam_id);

-- [FIX] usuario_rol no tenía ninguna restricción de unicidad: la base
-- vieja acepta asignar el mismo rol al mismo usuario N veces, y de hecho
-- nada lo impide hoy. Con 68 usuarios y 66 filas conviene verificar antes
-- del cutover (la consulta está en ORDEN.md).
ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_usu_rol_unique UNIQUE (usu_id, rol_id);

-- Unicidad de asistencia. En la base vieja cada una de estas está
-- duplicada como constraint + índice único idéntico
-- (idx_asistencia_auxiliar_unique_with_school y su par). Queda la
-- constraint, que ya crea su índice.
ALTER TABLE ONLY public.asistencia_auxiliar
    ADD CONSTRAINT uq_auxiliar_fecha_colegio UNIQUE (usu_id, asisaux_fecha, col_id);
ALTER TABLE ONLY public.asistencia_entrenador
    ADD CONSTRAINT uq_entrenador_fecha_colegio UNIQUE (ent_id, asisent_fecha, col_id);
ALTER TABLE ONLY public.asistencia_nino
    ADD CONSTRAINT uq_nino_fecha_sesion UNIQUE (nino_id, colacthor_id, asisnino_fecha);

-- [FIX] Correo único case-insensitive, en lugar del UNIQUE simple de la
-- base vieja. Ver la nota en la definición de usuario.
CREATE UNIQUE INDEX usuario_usu_correo_lower_key
    ON public.usuario (lower(trim(usu_correo)));

-- [FIX] Un usuario de Auth no puede estar enlazado a dos filas de usuario.
CREATE UNIQUE INDEX usuario_auth_user_id_key
    ON public.usuario (auth_user_id)
    WHERE auth_user_id IS NOT NULL;

-- =====================================================================
-- 11. FOREIGN KEYS
-- =====================================================================

ALTER TABLE ONLY public.actividad
    ADD CONSTRAINT actividad_cat_id_fkey FOREIGN KEY (cat_id)
    REFERENCES public.categoria(cat_id);

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);
ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_usu_id_fkey FOREIGN KEY (usu_id)
    REFERENCES public.usuario(usu_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.rol(rol_id);
ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.rol(rol_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_col_id_fkey FOREIGN KEY (col_id)
    REFERENCES public.colegio(col_id);
ALTER TABLE ONLY public.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_usu_id_fkey FOREIGN KEY (usu_id)
    REFERENCES public.usuario(usu_id);

ALTER TABLE ONLY public.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_col_id_fkey FOREIGN KEY (col_id)
    REFERENCES public.colegio(col_id);
ALTER TABLE ONLY public.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_act_id_fkey FOREIGN KEY (act_id)
    REFERENCES public.actividad(act_id);
ALTER TABLE ONLY public.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_dia_id_fkey FOREIGN KEY (dia_id)
    REFERENCES public.dia(dia_id);
ALTER TABLE ONLY public.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

-- [FIX] La base vieja tiene DOS FKs de entrenador.ent_id a usuario.usu_id:
-- entrenador_ent_id_fkey (sin acción) y fk_entrenador_usuario (CASCADE).
-- Postgres las valida ambas en cada insert. Queda la de CASCADE.
ALTER TABLE ONLY public.entrenador
    ADD CONSTRAINT fk_entrenador_usuario FOREIGN KEY (ent_id)
    REFERENCES public.usuario(usu_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.entrenador
    ADD CONSTRAINT entrenador_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

ALTER TABLE ONLY public.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_ent_id_fkey FOREIGN KEY (ent_id)
    REFERENCES public.entrenador(ent_id);
ALTER TABLE ONLY public.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_colacthor_id_fkey FOREIGN KEY (colacthor_id)
    REFERENCES public.colegio_actividad_horario(colacthor_id);
ALTER TABLE ONLY public.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

ALTER TABLE ONLY public.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_ent_id_fkey FOREIGN KEY (ent_id)
    REFERENCES public.entrenador(ent_id);
ALTER TABLE ONLY public.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_usu_id_fkey FOREIGN KEY (usu_id)
    REFERENCES public.usuario(usu_id);
ALTER TABLE ONLY public.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.rol(rol_id);
ALTER TABLE ONLY public.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

ALTER TABLE ONLY public.nino
    ADD CONSTRAINT nino_col_id_fkey FOREIGN KEY (col_id)
    REFERENCES public.colegio(col_id);
ALTER TABLE ONLY public.nino
    ADD CONSTRAINT nino_catninograd_id_fkey FOREIGN KEY (catninograd_id)
    REFERENCES public.categoria_nino_grado(catninograd_id);
ALTER TABLE ONLY public.nino
    ADD CONSTRAINT nino_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

ALTER TABLE ONLY public.nino_asignacion
    ADD CONSTRAINT nino_asignacion_nino_id_fkey FOREIGN KEY (nino_id)
    REFERENCES public.nino(nino_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.nino_asignacion
    ADD CONSTRAINT nino_asignacion_colacthor_id_fkey FOREIGN KEY (colacthor_id)
    REFERENCES public.colegio_actividad_horario(colacthor_id);
ALTER TABLE ONLY public.nino_asignacion
    ADD CONSTRAINT nino_asignacion_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

ALTER TABLE ONLY public.padre
    ADD CONSTRAINT padre_usu_id_fkey FOREIGN KEY (usu_id)
    REFERENCES public.usuario(usu_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.nino_padre
    ADD CONSTRAINT nino_padre_nino_id_fkey FOREIGN KEY (nino_id)
    REFERENCES public.nino(nino_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.nino_padre
    ADD CONSTRAINT ninopadre_padre_id_fkey FOREIGN KEY (padre_id)
    REFERENCES public.padre(padre_id);

ALTER TABLE ONLY public.asistencia_nino
    ADD CONSTRAINT asistencia_nino_nino_id_fkey FOREIGN KEY (nino_id)
    REFERENCES public.nino(nino_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.asistencia_nino
    ADD CONSTRAINT asistencia_nino_colacthor_id_fkey FOREIGN KEY (colacthor_id)
    REFERENCES public.colegio_actividad_horario(colacthor_id);
ALTER TABLE ONLY public.asistencia_nino
    ADD CONSTRAINT asistencia_nino_asisest_id_fkey FOREIGN KEY (asisest_id)
    REFERENCES public.asistencia_estado(asisest_id);
ALTER TABLE ONLY public.asistencia_nino
    ADD CONSTRAINT asistencia_nino_usu_registrador_fkey FOREIGN KEY (usu_registrador)
    REFERENCES public.usuario(usu_id);

ALTER TABLE ONLY public.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_ent_id_fkey FOREIGN KEY (ent_id)
    REFERENCES public.entrenador(ent_id);
ALTER TABLE ONLY public.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_asisest_id_fkey FOREIGN KEY (asisest_id)
    REFERENCES public.asistencia_estado(asisest_id);
ALTER TABLE ONLY public.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_usu_registrador_fkey FOREIGN KEY (usu_registrador)
    REFERENCES public.usuario(usu_id);
ALTER TABLE ONLY public.asistencia_entrenador
    ADD CONSTRAINT fk_asistencia_entrenador_colegio FOREIGN KEY (col_id)
    REFERENCES public.colegio(col_id);

ALTER TABLE ONLY public.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_usu_id_fkey FOREIGN KEY (usu_id)
    REFERENCES public.usuario(usu_id);
ALTER TABLE ONLY public.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_asisest_id_fkey FOREIGN KEY (asisest_id)
    REFERENCES public.asistencia_estado(asisest_id);
ALTER TABLE ONLY public.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_usu_registrador_fkey FOREIGN KEY (usu_registrador)
    REFERENCES public.usuario(usu_id);
ALTER TABLE ONLY public.asistencia_auxiliar
    ADD CONSTRAINT fk_asistencia_auxiliar_colegio FOREIGN KEY (col_id)
    REFERENCES public.colegio(col_id);

ALTER TABLE ONLY public.evaluacion
    ADD CONSTRAINT evaluacion_eva_creador_fkey FOREIGN KEY (eva_creador)
    REFERENCES public.usuario(usu_id);
ALTER TABLE ONLY public.evaluacion
    ADD CONSTRAINT evaluacion_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

ALTER TABLE ONLY public.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_eva_id_fkey FOREIGN KEY (eva_id)
    REFERENCES public.evaluacion(eva_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_disciplina_colacthor_id_fkey FOREIGN KEY (colacthor_id)
    REFERENCES public.colegio_actividad_horario(colacthor_id);
ALTER TABLE ONLY public.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);

ALTER TABLE ONLY public.evaluacion_parametro
    ADD CONSTRAINT evaluacion_parametro_eva_id_fkey FOREIGN KEY (eva_id)
    REFERENCES public.evaluacion(eva_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.evaluacion_parametro
    ADD CONSTRAINT evaluacion_parametro_evatipometo_id_fkey FOREIGN KEY (evatipometo_id)
    REFERENCES public.evaluacion_tipo_metodo(evatipometo_id);

ALTER TABLE ONLY public.evaluacion_tiempo_rangos
    ADD CONSTRAINT evaluacion_tiempo_rangos_evaparam_id_fkey FOREIGN KEY (evaparam_id)
    REFERENCES public.evaluacion_parametro(evaparam_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_eva_id_fkey FOREIGN KEY (eva_id)
    REFERENCES public.evaluacion(eva_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_ninoasig_id_fkey FOREIGN KEY (ninoasig_id)
    REFERENCES public.nino_asignacion(ninoasig_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);
ALTER TABLE ONLY public.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_usu_id_registrador_fkey FOREIGN KEY (usu_id_registrador)
    REFERENCES public.usuario(usu_id);

ALTER TABLE ONLY public.evaluacion_intento
    ADD CONSTRAINT evaluacion_intento_evaparam_id_fkey FOREIGN KEY (evaparam_id)
    REFERENCES public.evaluacion_parametro(evaparam_id);
ALTER TABLE ONLY public.evaluacion_intento
    ADD CONSTRAINT evaluacion_intento_evaninopen_id_fkey FOREIGN KEY (evaninopen_id)
    REFERENCES public.evaluacion_nino_pendiente(evaninopen_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.encuesta
    ADD CONSTRAINT encuesta_encu_creador_fkey FOREIGN KEY (encu_creador)
    REFERENCES public.usuario(usu_id);
ALTER TABLE ONLY public.encuesta
    ADD CONSTRAINT encuesta_est_id_fkey FOREIGN KEY (est_id)
    REFERENCES public.estado(est_id);
ALTER TABLE ONLY public.encuesta_pregunta
    ADD CONSTRAINT encuesta_pregunta_encu_id_fkey FOREIGN KEY (encu_id)
    REFERENCES public.encuesta(encu_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.encuesta_pregunta
    ADD CONSTRAINT encuesta_pregunta_encutiporesp_id_fkey FOREIGN KEY (encutiporesp_id)
    REFERENCES public.encuesta_tipo_respuesta(encutiporesp_id);
ALTER TABLE ONLY public.encuesta_respondida
    ADD CONSTRAINT encuesta_respondida_encu_id_fkey FOREIGN KEY (encu_id)
    REFERENCES public.encuesta(encu_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.encuesta_respondida
    ADD CONSTRAINT encuesta_respondida_padre_id_fkey FOREIGN KEY (padre_id)
    REFERENCES public.padre(padre_id);
ALTER TABLE ONLY public.encuesta_respuesta
    ADD CONSTRAINT encuesta_respuesta_encurespo_id_fkey FOREIGN KEY (encurespo_id)
    REFERENCES public.encuesta_respondida(encurespo_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.encuesta_respuesta
    ADD CONSTRAINT encuesta_respuesta_encupreg_id_fkey FOREIGN KEY (encupreg_id)
    REFERENCES public.encuesta_pregunta(encupreg_id) ON DELETE CASCADE;

-- =====================================================================
-- 12. ÍNDICES
--
-- [FIX] La base vieja tiene 64 FKs y 6 índices, de los cuales 2 son
-- inútiles (idx_entrenador_ent_id e idx_padre_padre_id duplican el índice
-- de la PK) y 2 más duplican constraints unique. Es decir: prácticamente
-- ninguna FK tenía índice de respaldo. Cada join y cada borrado del padre
-- hacía scan completo de la tabla hija.
--
-- Aquí se indexa toda columna de FK que no quede ya cubierta como columna
-- inicial de una PK o de un unique. Los índices que la base vieja tenía y
-- sí servían (usuario_rol) se conservan.
-- =====================================================================

-- Usuarios y permisos
CREATE INDEX idx_usuario_est_id ON public.usuario (est_id);
CREATE INDEX idx_usuario_rol_usu_id ON public.usuario_rol (usu_id);
CREATE INDEX idx_usuario_rol_rol_id ON public.usuario_rol (rol_id);

-- Colegios, actividades, horarios
CREATE INDEX idx_actividad_cat_id ON public.actividad (cat_id);
CREATE INDEX idx_colegio_coordinador_usu_id ON public.colegio_coordinador (usu_id);
CREATE INDEX idx_cah_col_id ON public.colegio_actividad_horario (col_id);
CREATE INDEX idx_cah_act_id ON public.colegio_actividad_horario (act_id);
CREATE INDEX idx_cah_dia_id ON public.colegio_actividad_horario (dia_id);
CREATE INDEX idx_cah_est_id ON public.colegio_actividad_horario (est_id);

-- Entrenadores
CREATE INDEX idx_entrenador_est_id ON public.entrenador (est_id);
CREATE INDEX idx_entasig_ent_id ON public.entrenador_asignacion (ent_id);
CREATE INDEX idx_entasig_colacthor_id ON public.entrenador_asignacion (colacthor_id);
CREATE INDEX idx_entasig_est_id ON public.entrenador_asignacion (est_id);
CREATE INDEX idx_entaux_ent_id ON public.entrenador_auxiliar (ent_id);
CREATE INDEX idx_entaux_usu_id ON public.entrenador_auxiliar (usu_id);
CREATE INDEX idx_entaux_rol_id ON public.entrenador_auxiliar (rol_id);
CREATE INDEX idx_entaux_est_id ON public.entrenador_auxiliar (est_id);

-- Estudiantes y padres
CREATE INDEX idx_nino_col_id ON public.nino (col_id);
CREATE INDEX idx_nino_catninograd_id ON public.nino (catninograd_id);
CREATE INDEX idx_nino_est_id ON public.nino (est_id);
CREATE INDEX idx_ninoasig_colacthor_id ON public.nino_asignacion (colacthor_id);
CREATE INDEX idx_ninoasig_est_id ON public.nino_asignacion (est_id);
CREATE INDEX idx_padre_usu_id ON public.padre (usu_id);
CREATE INDEX idx_nino_padre_padre_id ON public.nino_padre (padre_id);

-- nino_asignacion (nino_id, colacthor_id): cubre la FK a nino y es
-- exactamente la búsqueda que hacen reactivate_nino_asignacion y el
-- trigger de insert.
CREATE INDEX idx_ninoasig_nino_colacthor
    ON public.nino_asignacion (nino_id, colacthor_id);

-- [FIX] Una sola asignación ACTIVA por (niño, horario).
-- reactivate_nino_asignacion() hace SELECT ... INTO sobre ese par
-- esperando una sola fila; en plpgsql eso no lanza error con varias filas,
-- se queda con una arbitraria. Es decir: hoy la reactivación puede tocar
-- la fila equivocada, en silencio.
-- El índice es PARCIAL a propósito. En la prod vieja hay 13 pares con dos
-- filas (26 en total) — histórico legítimo de bajas y reinscripciones — así
-- que un unique total rechazaría la carga del cutover. Verificado en prod
-- el 2026-07-29: pares con más de una fila activa = 0, o sea que esta
-- restricción se cumple con los datos reales.
CREATE UNIQUE INDEX ninoasig_una_activa_por_horario
    ON public.nino_asignacion (nino_id, colacthor_id)
    WHERE est_id = 1;

-- Asistencias. Los índices por fecha son para los reportes, que hoy
-- filtran por rango y no tienen por dónde entrar.
CREATE INDEX idx_asisnino_asisest_id ON public.asistencia_nino (asisest_id);
CREATE INDEX idx_asisnino_usu_registrador ON public.asistencia_nino (usu_registrador);
CREATE INDEX idx_asisnino_colacthor_fecha
    ON public.asistencia_nino (colacthor_id, asisnino_fecha);
CREATE INDEX idx_asisnino_fecha ON public.asistencia_nino (asisnino_fecha);

CREATE INDEX idx_asisent_asisest_id ON public.asistencia_entrenador (asisest_id);
CREATE INDEX idx_asisent_usu_registrador ON public.asistencia_entrenador (usu_registrador);
CREATE INDEX idx_asisent_col_fecha
    ON public.asistencia_entrenador (col_id, asisent_fecha);
CREATE INDEX idx_asisent_fecha ON public.asistencia_entrenador (asisent_fecha);

CREATE INDEX idx_asisaux_asisest_id ON public.asistencia_auxiliar (asisest_id);
CREATE INDEX idx_asisaux_usu_registrador ON public.asistencia_auxiliar (usu_registrador);
CREATE INDEX idx_asisaux_col_fecha
    ON public.asistencia_auxiliar (col_id, asisaux_fecha);
CREATE INDEX idx_asisaux_fecha ON public.asistencia_auxiliar (asisaux_fecha);

-- Evaluaciones
CREATE INDEX idx_evaluacion_eva_creador ON public.evaluacion (eva_creador);
CREATE INDEX idx_evaluacion_est_id ON public.evaluacion (est_id);
CREATE INDEX idx_evaasig_colacthor_id ON public.evaluacion_asignacion (colacthor_id);
CREATE INDEX idx_evaasig_est_id ON public.evaluacion_asignacion (est_id);
CREATE INDEX idx_evaparam_eva_id ON public.evaluacion_parametro (eva_id);
CREATE INDEX idx_evaparam_evatipometo_id ON public.evaluacion_parametro (evatipometo_id);
CREATE INDEX idx_evaninopen_eva_id ON public.evaluacion_nino_pendiente (eva_id);
CREATE INDEX idx_evaninopen_ninoasig_id ON public.evaluacion_nino_pendiente (ninoasig_id);
CREATE INDEX idx_evaninopen_est_id ON public.evaluacion_nino_pendiente (est_id);
CREATE INDEX idx_evaninopen_usu_registrador
    ON public.evaluacion_nino_pendiente (usu_id_registrador);
CREATE INDEX idx_evaint_evaparam_id ON public.evaluacion_intento (evaparam_id);
CREATE INDEX idx_evaint_evaninopen_id ON public.evaluacion_intento (evaninopen_id);

-- Encuestas
CREATE INDEX idx_encuesta_creador ON public.encuesta (encu_creador);
CREATE INDEX idx_encuesta_est_id ON public.encuesta (est_id);
CREATE INDEX idx_encupreg_encu_id ON public.encuesta_pregunta (encu_id);
CREATE INDEX idx_encupreg_tiporesp_id ON public.encuesta_pregunta (encutiporesp_id);
CREATE INDEX idx_encurespo_encu_id ON public.encuesta_respondida (encu_id);
CREATE INDEX idx_encurespo_padre_id ON public.encuesta_respondida (padre_id);
CREATE INDEX idx_encurespu_encurespo_id ON public.encuesta_respuesta (encurespo_id);
CREATE INDEX idx_encurespu_encupreg_id ON public.encuesta_respuesta (encupreg_id);

-- =====================================================================
-- 13. FUNCIONES
--
-- [FIX] handle_new_user() NO se replica. Insertaba en public.profiles,
-- una tabla que no existe en la base: es residuo del scaffold de Lovable.
-- Si quedó un trigger sobre auth.users invocándola, toda alta en Supabase
-- Auth falla — justo lo que la Fase 5 necesita que funcione.
--
-- [FIX] A las funciones SECURITY DEFINER se les fija search_path. Sin eso,
-- quien controle el search_path de la sesión puede hacer que la función
-- resuelva nombres contra otro schema. delete_student_evaluation no lo
-- tenía.
-- =====================================================================

CREATE FUNCTION public.delete_student_evaluation(p_evaninopen_id integer)
    RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  -- Borra todos los intentos de esta evaluación
  DELETE FROM evaluacion_intento
  WHERE evaninopen_id = p_evaninopen_id;

  -- Devuelve la evaluación del estudiante a pendiente (est_id = 6)
  UPDATE evaluacion_nino_pendiente
  SET est_id = 6,
      usu_id_registrador = NULL,
      evaninopen_fecha_finalizacion = NULL
  WHERE evaninopen_id = p_evaninopen_id;
END;
$$;

CREATE FUNCTION public.handle_nino_asignacion_insert()
    RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
DECLARE
    eval_record RECORD;
BEGIN
    -- Al inscribir un estudiante en un horario, se le crean las
    -- evaluaciones pendientes de las evaluaciones activas de ese horario.
    FOR eval_record IN
        SELECT eva_id
        FROM evaluacion_asignacion
        WHERE colacthor_id = NEW.colacthor_id
          AND est_id = 1
    LOOP
        IF EXISTS (
            SELECT 1
            FROM evaluacion_nino_pendiente
            WHERE ninoasig_id = NEW.ninoasig_id
              AND eva_id = eval_record.eva_id
        ) THEN
            -- Existe: si estaba inactiva, se reactiva como pendiente
            UPDATE evaluacion_nino_pendiente
            SET est_id = 6
            WHERE ninoasig_id = NEW.ninoasig_id
              AND eva_id = eval_record.eva_id
              AND est_id = 2;
        ELSE
            INSERT INTO evaluacion_nino_pendiente (
                eva_id, ninoasig_id, est_id, usu_id_registrador
            ) VALUES (
                eval_record.eva_id, NEW.ninoasig_id, 6, NULL
            );
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.handle_nino_asignacion_insert() IS
    'Se le quitó un SELECT a existing_ninoasig_id cuyo resultado no se usaba: '
    'la versión vieja lo calculaba y lo descartaba.';

CREATE FUNCTION public.handle_nino_asignacion_update()
    RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
    -- Si la asignación se da de baja (est_id 1 -> 2), se inactivan sus
    -- evaluaciones pendientes.
    IF OLD.est_id = 1 AND NEW.est_id = 2 THEN
        UPDATE evaluacion_nino_pendiente
        SET est_id = 2
        WHERE ninoasig_id = NEW.ninoasig_id
          AND est_id IN (1, 6, 7);
    END IF;

    RETURN NEW;
END;
$$;

CREATE FUNCTION public.reactivate_nino_asignacion(
        p_nino_id integer,
        p_colacthor_id integer)
    RETURNS integer
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
DECLARE
    existing_ninoasig_id INTEGER;
    eval_record RECORD;
BEGIN
    SELECT ninoasig_id INTO existing_ninoasig_id
    FROM nino_asignacion
    WHERE nino_id = p_nino_id
      AND colacthor_id = p_colacthor_id
      AND est_id <> 1;

    IF existing_ninoasig_id IS NULL THEN
        RETURN NULL;
    END IF;

    UPDATE nino_asignacion
    SET est_id = 1,
        ninoasig_fecha_inscripcion = now(),
        ninoasig_fecha_baja = NULL
    WHERE ninoasig_id = existing_ninoasig_id;

    FOR eval_record IN
        SELECT eva_id
        FROM evaluacion_asignacion
        WHERE colacthor_id = p_colacthor_id
          AND est_id = 1
    LOOP
        IF EXISTS (
            SELECT 1
            FROM evaluacion_nino_pendiente
            WHERE ninoasig_id = existing_ninoasig_id
              AND eva_id = eval_record.eva_id
        ) THEN
            UPDATE evaluacion_nino_pendiente
            SET est_id = 6
            WHERE ninoasig_id = existing_ninoasig_id
              AND eva_id = eval_record.eva_id
              AND est_id = 2;
        ELSE
            INSERT INTO evaluacion_nino_pendiente (
                eva_id, ninoasig_id, est_id, usu_id_registrador
            ) VALUES (
                eval_record.eva_id, existing_ninoasig_id, 6, NULL
            );
        END IF;
    END LOOP;

    RETURN existing_ninoasig_id;
END;
$$;

CREATE FUNCTION public.set_role_permissions(
        p_actor_usu_id integer,
        p_target_rol_id integer,
        p_enable_modules text[] DEFAULT ARRAY[]::text[],
        p_disable_modules text[] DEFAULT ARRAY[]::text[],
        p_action text DEFAULT 'ver'::text)
    RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  -- Solo Admin PVCAR (rol_id = 1) puede administrar permisos
  IF NOT EXISTS (
    SELECT 1
    FROM public.usuario_rol ur
    WHERE ur.usu_id = p_actor_usu_id
      AND ur.rol_id = 1
  ) THEN
    RAISE EXCEPTION 'Not authorized to manage role permissions';
  END IF;

  IF p_enable_modules IS NULL THEN
    p_enable_modules := ARRAY[]::text[];
  END IF;
  IF p_disable_modules IS NULL THEN
    p_disable_modules := ARRAY[]::text[];
  END IF;

  INSERT INTO public.rol_permiso (rol_id, modulo, accion)
  SELECT p_target_rol_id, m, p_action
  FROM unnest(p_enable_modules) AS m
  ON CONFLICT (rol_id, modulo, accion) DO NOTHING;

  DELETE FROM public.rol_permiso
  WHERE rol_id = p_target_rol_id
    AND accion = p_action
    AND modulo = ANY (p_disable_modules);
END;
$$;

COMMENT ON FUNCTION public.set_role_permissions(integer, integer, text[], text[], text) IS
    'Fija permisos de un rol: upsert de los módulos habilitados, delete de los deshabilitados. '
    'Solo Admin PVCAR (rol_id=1). El backend valida permisos por su cuenta; esta RPC se '
    'conserva por paridad y como segunda barrera.';

CREATE FUNCTION public.update_evaluacion_puntaje_total()
    RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
DECLARE
    target_eva_id INTEGER;
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_eva_id := OLD.eva_id;
    ELSE
        target_eva_id := NEW.eva_id;
    END IF;

    UPDATE evaluacion
    SET eva_puntaje_total = (
        SELECT COALESCE(SUM(evaparam_puntaje), 0)
        FROM evaluacion_parametro ep
        WHERE ep.eva_id = target_eva_id
    )
    WHERE eva_id = target_eva_id;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

-- =====================================================================
-- 14. TRIGGERS
-- =====================================================================

CREATE TRIGGER trigger_nino_asignacion_evaluation
    AFTER INSERT ON public.nino_asignacion
    FOR EACH ROW EXECUTE FUNCTION public.handle_nino_asignacion_insert();

CREATE TRIGGER trigger_nino_asignacion_update
    AFTER UPDATE ON public.nino_asignacion
    FOR EACH ROW EXECUTE FUNCTION public.handle_nino_asignacion_update();

CREATE TRIGGER trigger_update_evaluacion_puntaje_total
    AFTER INSERT OR DELETE OR UPDATE ON public.evaluacion_parametro
    FOR EACH ROW EXECUTE FUNCTION public.update_evaluacion_puntaje_total();

COMMIT;

-- =====================================================================
-- PENDIENTE DE DECISIÓN
--
-- Cosas que la base vieja hace y que aquí se replicaron TAL CUAL, a
-- propósito, para no romper la paridad funcional antes de compararla.
-- Cada una es un candidato a corregir en una migración posterior.
--
-- 1. nino_asignacion.ninoasig_fecha_baja tiene DEFAULT now(). Una
--    asignación recién creada nace con fecha de baja. reactivate_...()
--    la pone en NULL al reactivar, así que el dato es incoherente según
--    el camino por el que se creó la fila. Debería ser DEFAULT NULL.
--
-- 2. nino_asignacion.est_id es nullable y sin default, aunque toda la
--    lógica asume 1 = activo. Debería ser NOT NULL DEFAULT 1.
--
-- 3. asistencia_*.hora_tarde es `time DEFAULT now()`: toda fila nace con
--    la hora del insert, aunque la asistencia no sea tardía. El campo no
--    distingue "no aplica" de "llegó a esta hora".
--
-- 4. evaluacion_intento.evaninopen_id es nullable, pero un intento sin
--    evaluación pendiente no significa nada. Debería ser NOT NULL.
--
-- 5. entrenador_asignacion no tiene UNIQUE (ent_id, colacthor_id). En la
--    prod vieja hay 1 par duplicado. Puede ser histórico legítimo, igual
--    que en nino_asignacion, pero ahí la lógica no depende de que sea
--    único, así que no se restringe sin confirmarlo con el cliente.
--
-- Resueltos ya, con verificación contra los datos de producción
-- (2026-07-29, solo lectura):
--   - Correos que colisionan sin distinguir mayúsculas: 0. El índice único
--     sobre lower(trim(usu_correo)) es seguro.
--   - Duplicados en usuario_rol: 0. El UNIQUE nuevo es seguro.
--   - nino_asignacion: 13 pares con dos filas, pero 0 pares con más de una
--     ACTIVA. De ahí el índice único parcial.
--   - Usuarios: 50 activos, 18 inactivos. Los 50 activos necesitan cuenta
--     en Auth antes de que el CHECK los deje entrar (Fase 5, Anexo A).
--
-- HALLAZGO APARTE, en la base VIEJA (no aplica aquí, pero explica cosas):
--   auth.users tiene el trigger on_auth_user_created que ejecuta
--   handle_new_user(), y esa función inserta en public.profiles, que NO
--   existe. O sea: en la prod actual, crear un usuario en Supabase Auth
--   FALLA siempre. Nadie lo notó porque el login va por usu_contrasena en
--   texto plano. En la base nueva ni la función ni el trigger se recrean;
--   por eso el backfill de la Fase 5 puede funcionar.
-- =====================================================================
