-- =====================================================================
-- PVCAR — 0013_archivo.sql
-- El esquema `archivo`: copia congelada de la plataforma vieja, solo lectura.
--
-- Va en PVCAR_Dev y en PVCAR. Solo crea la ESTRUCTURA (35 tablas vacías);
-- los datos entran con carga_archivo_2026-10-01.sql, que NO va al repo.
-- Todo en una transacción. Si `archivo` ya existe, se niega a correr.
--
-- ---------------------------------------------------------------------
-- Por qué existe
--
-- Decisión del cliente del 2026-10-01: la plataforma nueva arranca de
-- cero (el admin crea todo) y lo de la vieja se conserva solo para
-- consultar, en Reportes > "Data anterior". Va en un esquema aparte para
-- que no aparezca en ninguna lista ni consulta de `public`.
--
-- Es la estructura de la base VIEJA (no la de `public` de hoy), tal cual
-- salió del respaldo Backup_bd/prod_full_2026-10-01.dump, con estos cambios:
--   - sin triggers ni funciones: es una foto fija, nadie escribe aquí;
--   - sin la política "Anyone can read rol_permiso" del sistema viejo;
--   - columnas fuera: usuario.usu_contrasena (texto plano), usuario.usu_foto,
--     nino.nino_info_salud, nino.nino_otra_info, nino.nino_cedula,
--     nino.nino_foto, colegio.col_rep_foto. Las fotos apuntaban al bucket
--     viejo, que se borrará. Lo quitado sigue en el respaldo completo.
--
-- Misma cerradura que `public`: RLS activo y forzado, cero políticas,
-- anon/authenticated sin nada. service_role solo LEE.
-- =====================================================================

BEGIN;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'archivo') THEN
        RAISE EXCEPTION 'El esquema archivo ya existe: 0013 ya está aplicada.';
    END IF;
END
$$;

CREATE SCHEMA archivo;

--
-- Name: SCHEMA archivo; Type: COMMENT; Schema: -; Owner: -
--

--
-- Name: actividad; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.actividad (
    act_id integer NOT NULL,
    cat_id integer,
    act_nombre text NOT NULL,
    act_descripcion text,
    act_espacio_trabajo text,
    act_tipo_espacio text,
    act_espacio_secundario text,
    act_indumentaria_tipo text,
    act_materiales_alumno text[],
    act_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    act_fecha_modificacion timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: actividad_act_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.actividad ALTER COLUMN act_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.actividad_act_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: asistencia_auxiliar; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.asistencia_auxiliar (
    asisaux_id bigint NOT NULL,
    asisaux_fecha date NOT NULL,
    usu_id integer NOT NULL,
    asisest_id smallint NOT NULL,
    asisaux_hora_tarde time without time zone DEFAULT now(),
    usu_registrador integer NOT NULL,
    asisaux_fecha_registrado timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    asisaux_razon_justificado text,
    col_id integer NOT NULL
);

--
-- Name: asistencia_auxiliar_asisaux_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.asistencia_auxiliar ALTER COLUMN asisaux_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.asistencia_auxiliar_asisaux_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: asistencia_entrenador; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.asistencia_entrenador (
    asisent_id bigint NOT NULL,
    asisent_fecha date NOT NULL,
    ent_id integer NOT NULL,
    asisest_id smallint NOT NULL,
    asisent_hora_tarde time without time zone DEFAULT now(),
    usu_registrador integer NOT NULL,
    asisent_fecha_registrado timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    asisent_razon_justificado text,
    col_id integer NOT NULL
);

--
-- Name: asistencia_entrenador_asisent_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.asistencia_entrenador ALTER COLUMN asisent_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.asistencia_entrenador_asisent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: asistencia_estado; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.asistencia_estado (
    asisest_id smallint NOT NULL,
    asisest_nombre text NOT NULL
);

--
-- Name: asistencia_estado_asisest_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.asistencia_estado ALTER COLUMN asisest_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.asistencia_estado_asisest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: asistencia_nino; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.asistencia_nino (
    asisnino_id bigint NOT NULL,
    nino_id integer NOT NULL,
    asisest_id smallint NOT NULL,
    usu_registrador integer NOT NULL,
    asisnino_fecha date NOT NULL,
    asisnino_hora_tarde time without time zone DEFAULT now(),
    asisnino_razon_justificado text,
    asisnino_fecha_registrado timestamp with time zone DEFAULT now() NOT NULL,
    colacthor_id integer NOT NULL
);

--
-- Name: asistencia_nino_asisnino_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.asistencia_nino ALTER COLUMN asisnino_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.asistencia_nino_asisnino_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: categoria; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.categoria (
    cat_id integer NOT NULL,
    cat_nombre text NOT NULL,
    cat_descripcion text
);

--
-- Name: categoria_cat_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.categoria ALTER COLUMN cat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.categoria_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: encuesta_tipo_respuesta; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.encuesta_tipo_respuesta (
    encutiporesp_id smallint NOT NULL,
    encutiporesp_nombre text NOT NULL
);

--
-- Name: categoria_encuesta_respuesta_catencuresp_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.encuesta_tipo_respuesta ALTER COLUMN encutiporesp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.categoria_encuesta_respuesta_catencuresp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: categoria_nino_grado; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.categoria_nino_grado (
    catninograd_id smallint NOT NULL,
    catninograd_nombre text NOT NULL
);

--
-- Name: categoria_nino_grado_catninograd_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.categoria_nino_grado ALTER COLUMN catninograd_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.categoria_nino_grado_catninograd_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: colegio; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.colegio (
    col_id integer NOT NULL,
    col_nombre text NOT NULL,
    col_direccion text NOT NULL,
    col_rep_nombre text,
    col_rep_telefono text,
    col_rep_email text,
    col_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    col_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: colegio_actividad_horario; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.colegio_actividad_horario (
    colacthor_id integer NOT NULL,
    col_id integer,
    act_id integer,
    dia_id smallint,
    colacthor_hora_inicio time without time zone,
    colacthor_hora_fin time without time zone,
    est_id smallint DEFAULT '1'::smallint,
    colacthor_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: colegio_actividad_horario_colacthor_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.colegio_actividad_horario ALTER COLUMN colacthor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.colegio_actividad_horario_colacthor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: colegio_col_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.colegio ALTER COLUMN col_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.colegio_col_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: colegio_coordinador; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.colegio_coordinador (
    colcoor_id integer NOT NULL,
    col_id integer NOT NULL,
    usu_id integer NOT NULL
);

--
-- Name: colegio_coordinador_colcoor_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.colegio_coordinador ALTER COLUMN colcoor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.colegio_coordinador_colcoor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: dia; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.dia (
    dia_id smallint NOT NULL,
    dia_nombre text NOT NULL
);

--
-- Name: dia_dia_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.dia ALTER COLUMN dia_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.dia_dia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: encuesta; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.encuesta (
    encu_id integer NOT NULL,
    encu_titulo text NOT NULL,
    encu_descripcion text,
    encu_creador integer NOT NULL,
    est_id smallint NOT NULL,
    encu_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    encu_fecha_modificacion timestamp with time zone DEFAULT now()
);

--
-- Name: encuesta_encu_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.encuesta ALTER COLUMN encu_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.encuesta_encu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: encuesta_pregunta; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.encuesta_pregunta (
    encupreg_id bigint NOT NULL,
    encu_id integer NOT NULL,
    encupreg_orden smallint NOT NULL,
    encupreg_pregunta text NOT NULL,
    encupreg_nota text,
    encutiporesp_id smallint NOT NULL,
    encupreg_escala_min smallint,
    encupreg_escala_max smallint
);

--
-- Name: encuesta_pregunta_encupreg_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.encuesta_pregunta ALTER COLUMN encupreg_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.encuesta_pregunta_encupreg_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: encuesta_respondida; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.encuesta_respondida (
    encurespo_id integer NOT NULL,
    encu_id integer NOT NULL,
    padre_id integer NOT NULL,
    encurespo_fecha_registro timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: encuesta_respondida_encurespo_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.encuesta_respondida ALTER COLUMN encurespo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.encuesta_respondida_encurespo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: encuesta_respuesta; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.encuesta_respuesta (
    encurespu_id bigint NOT NULL,
    encurespo_id integer NOT NULL,
    encupreg_id bigint NOT NULL,
    encurespu_texto text,
    encurespu_num numeric,
    encurespu_fecha timestamp with time zone,
    encurespu_hora time with time zone,
    encurespu_sino boolean
);

--
-- Name: encuesta_respuesta_encurespu_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.encuesta_respuesta ALTER COLUMN encurespu_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.encuesta_respuesta_encurespu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: entrenador; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.entrenador (
    ent_id integer NOT NULL,
    ent_cedula text,
    ent_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ent_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    est_id smallint DEFAULT '1'::smallint NOT NULL
);

--
-- Name: entrenador_asignacion; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.entrenador_asignacion (
    entasig_id integer NOT NULL,
    ent_id integer,
    colacthor_id integer,
    entasig_fecha_inicio date NOT NULL,
    entasig_fecha_fin date,
    est_id smallint DEFAULT '1'::smallint NOT NULL
);

--
-- Name: entrenador_asignacion_entasig_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.entrenador_asignacion ALTER COLUMN entasig_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.entrenador_asignacion_entasig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: entrenador_auxiliar; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.entrenador_auxiliar (
    entaux_id smallint NOT NULL,
    usu_id integer,
    rol_id integer,
    est_id smallint DEFAULT '1'::smallint,
    ent_id integer
);

--
-- Name: entrenador_auxiliar_entaux_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.entrenador_auxiliar ALTER COLUMN entaux_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.entrenador_auxiliar_entaux_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: estado; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.estado (
    est_id smallint NOT NULL,
    est_nombre text NOT NULL
);

--
-- Name: estado_est_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.estado ALTER COLUMN est_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.estado_est_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: evaluacion; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.evaluacion (
    eva_id integer NOT NULL,
    eva_creador integer NOT NULL,
    est_id smallint DEFAULT '1'::smallint NOT NULL,
    eva_titulo text NOT NULL,
    eva_descripcion text,
    eva_fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    eva_categoria text,
    eva_puntaje_total numeric(10,2) DEFAULT 0
);

--
-- Name: evaluacion_asignacion; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.evaluacion_asignacion (
    evaasig_id smallint NOT NULL,
    eva_id integer NOT NULL,
    colacthor_id integer NOT NULL,
    est_id smallint DEFAULT '1'::smallint
);

--
-- Name: evaluacion_actividad_evaact_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.evaluacion_asignacion ALTER COLUMN evaasig_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.evaluacion_actividad_evaact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: evaluacion_eva_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.evaluacion ALTER COLUMN eva_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.evaluacion_eva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: evaluacion_intento; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.evaluacion_intento (
    evaint_id bigint NOT NULL,
    evaparam_id integer NOT NULL,
    evaint_intento smallint NOT NULL,
    evaint_tiempo integer,
    evaint_logro boolean,
    evaint_num smallint,
    evaninopen_id integer,
    evaint_mobak smallint,
    evaint_puntaje_obtenido real
);

--
-- Name: evaluacion_intento_evaint_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.evaluacion_intento ALTER COLUMN evaint_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.evaluacion_intento_evaint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: evaluacion_nino_pendiente; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.evaluacion_nino_pendiente (
    evaninopen_id integer NOT NULL,
    eva_id integer,
    ninoasig_id integer NOT NULL,
    est_id smallint DEFAULT '6'::smallint NOT NULL,
    usu_id_registrador integer,
    evaninopen_fecha_finalizacion timestamp with time zone
);

--
-- Name: evaluacion_nino_pendiente_evaninopen_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.evaluacion_nino_pendiente ALTER COLUMN evaninopen_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.evaluacion_nino_pendiente_evaninopen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: evaluacion_parametro; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.evaluacion_parametro (
    evaparam_id integer NOT NULL,
    eva_id integer NOT NULL,
    evaparam_nombre text NOT NULL,
    evaparam_nota text,
    evatipometo_id smallint,
    evaparam_intentos smallint,
    evaparam_escala_min smallint,
    evaparam_escala_max smallint,
    evaparam_puntaje smallint NOT NULL,
    CONSTRAINT evaluacion_parametro_evaparam_intentos_check CHECK ((evaparam_intentos >= 1))
);

--
-- Name: COLUMN evaluacion_parametro.evaparam_puntaje; Type: COMMENT; Schema: archivo; Owner: -
--

COMMENT ON COLUMN archivo.evaluacion_parametro.evaparam_puntaje IS 'Puntaje del parámetro asignado manualmente pero se divide en la cantidad de intentos';

--
-- Name: evaluacion_parametro_evaparam_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

CREATE SEQUENCE archivo.evaluacion_parametro_evaparam_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: evaluacion_parametro_evaparam_id_seq; Type: SEQUENCE OWNED BY; Schema: archivo; Owner: -
--

ALTER SEQUENCE archivo.evaluacion_parametro_evaparam_id_seq OWNED BY archivo.evaluacion_parametro.evaparam_id;

--
-- Name: evaluacion_tiempo_rangos; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.evaluacion_tiempo_rangos (
    evatieran_id integer NOT NULL,
    evaparam_id integer NOT NULL,
    evatieran_op_cero text NOT NULL,
    evatieran_tiempo_cero integer NOT NULL,
    evatieran_op_full text NOT NULL,
    evatieran_tiempo_full integer NOT NULL,
    CONSTRAINT check_different_times CHECK ((evatieran_tiempo_cero <> evatieran_tiempo_full)),
    CONSTRAINT check_max_op CHECK ((evatieran_op_full = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text]))),
    CONSTRAINT check_max_tiempo_positive CHECK ((evatieran_tiempo_full > 0)),
    CONSTRAINT check_min_op CHECK ((evatieran_op_cero = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text]))),
    CONSTRAINT check_min_tiempo_positive CHECK ((evatieran_tiempo_cero > 0)),
    CONSTRAINT evaluacion_tiempo_rangos_check CHECK ((((evatieran_op_cero = ANY (ARRAY['<'::text, '<='::text])) AND (evatieran_op_full = ANY (ARRAY['>'::text, '>='::text])) AND (evatieran_tiempo_full > evatieran_tiempo_cero)) OR ((evatieran_op_cero = ANY (ARRAY['>'::text, '>='::text])) AND (evatieran_op_full = ANY (ARRAY['<'::text, '<='::text])) AND (evatieran_tiempo_full < evatieran_tiempo_cero)))),
    CONSTRAINT evaluacion_tiempo_rangos_check1 CHECK ((evatieran_tiempo_cero <> evatieran_tiempo_full)),
    CONSTRAINT evaluacion_tiempo_rangos_evatieran_max_op_check CHECK ((evatieran_op_full = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text]))),
    CONSTRAINT evaluacion_tiempo_rangos_evatieran_min_op_check CHECK ((evatieran_op_cero = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text])))
);

--
-- Name: evaluacion_tiempo_rangos_evatieran_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

CREATE SEQUENCE archivo.evaluacion_tiempo_rangos_evatieran_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: evaluacion_tiempo_rangos_evatieran_id_seq; Type: SEQUENCE OWNED BY; Schema: archivo; Owner: -
--

ALTER SEQUENCE archivo.evaluacion_tiempo_rangos_evatieran_id_seq OWNED BY archivo.evaluacion_tiempo_rangos.evatieran_id;

--
-- Name: evaluacion_tipo_metodo; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.evaluacion_tipo_metodo (
    evatipometo_id smallint NOT NULL,
    evatipometo_nombre text NOT NULL
);

--
-- Name: evaluacion_tipo_metodo_evatipometo_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.evaluacion_tipo_metodo ALTER COLUMN evatipometo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.evaluacion_tipo_metodo_evatipometo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: nino; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.nino (
    nino_id integer NOT NULL,
    nino_nombre text NOT NULL,
    nino_edad smallint,
    nino_toma_transporte boolean,
    nino_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    nino_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    col_id integer NOT NULL,
    catninograd_id smallint,
    est_id smallint DEFAULT '1'::smallint
);

--
-- Name: nino_asignacion; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.nino_asignacion (
    ninoasig_id integer NOT NULL,
    nino_id integer NOT NULL,
    colacthor_id integer NOT NULL,
    ninoasig_fecha_inscripcion timestamp with time zone DEFAULT now() NOT NULL,
    ninoasig_fecha_baja timestamp with time zone DEFAULT now(),
    est_id smallint
);

--
-- Name: nino_asignacion_ninoasg_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.nino_asignacion ALTER COLUMN ninoasig_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.nino_asignacion_ninoasg_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: nino_nino_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.nino ALTER COLUMN nino_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.nino_nino_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: nino_padre; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.nino_padre (
    ninopadre_id integer NOT NULL,
    nino_id integer,
    padre_id integer
);

--
-- Name: ninopadre_ninopadre_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.nino_padre ALTER COLUMN ninopadre_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.ninopadre_ninopadre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: padre; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.padre (
    padre_id integer NOT NULL,
    padre_sector_residencia text,
    padre_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    padre_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    usu_id integer
);

--
-- Name: padre_padre_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.padre ALTER COLUMN padre_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.padre_padre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: rol; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.rol (
    rol_id integer NOT NULL,
    rol_nombre text NOT NULL,
    rol_titulo text NOT NULL,
    rol_descripcion text
);

--
-- Name: rol_permiso; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.rol_permiso (
    rolper_id integer NOT NULL,
    rol_id integer NOT NULL,
    modulo text NOT NULL,
    accion text DEFAULT 'ver'::text NOT NULL
);

--
-- Name: rol_permiso_rolper_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

CREATE SEQUENCE archivo.rol_permiso_rolper_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: rol_permiso_rolper_id_seq; Type: SEQUENCE OWNED BY; Schema: archivo; Owner: -
--

ALTER SEQUENCE archivo.rol_permiso_rolper_id_seq OWNED BY archivo.rol_permiso.rolper_id;

--
-- Name: rol_rol_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.rol ALTER COLUMN rol_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME archivo.rol_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: usuario; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.usuario (
    usu_id integer NOT NULL,
    usu_nombre text NOT NULL,
    usu_correo text NOT NULL,
    usu_telefono text,
    usu_fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    usu_fecha_modificacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    est_id smallint DEFAULT '1'::smallint NOT NULL
);

--
-- Name: usuario_rol; Type: TABLE; Schema: archivo; Owner: -
--

CREATE TABLE archivo.usuario_rol (
    usurol_id integer NOT NULL,
    usu_id integer NOT NULL,
    rol_id integer NOT NULL
);

--
-- Name: usuario_rol_usurol_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.usuario_rol ALTER COLUMN usurol_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.usuario_rol_usurol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: usuario_usu_id_seq; Type: SEQUENCE; Schema: archivo; Owner: -
--

ALTER TABLE archivo.usuario ALTER COLUMN usu_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME archivo.usuario_usu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: evaluacion_parametro evaparam_id; Type: DEFAULT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_parametro ALTER COLUMN evaparam_id SET DEFAULT nextval('archivo.evaluacion_parametro_evaparam_id_seq'::regclass);

--
-- Name: evaluacion_tiempo_rangos evatieran_id; Type: DEFAULT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_tiempo_rangos ALTER COLUMN evatieran_id SET DEFAULT nextval('archivo.evaluacion_tiempo_rangos_evatieran_id_seq'::regclass);

--
-- Name: rol_permiso rolper_id; Type: DEFAULT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.rol_permiso ALTER COLUMN rolper_id SET DEFAULT nextval('archivo.rol_permiso_rolper_id_seq'::regclass);

--
-- Name: actividad actividad_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.actividad
    ADD CONSTRAINT actividad_pkey PRIMARY KEY (act_id);

--
-- Name: asistencia_auxiliar asistencia_auxiliar_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_pkey PRIMARY KEY (asisaux_id);

--
-- Name: asistencia_entrenador asistencia_entrenador_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_pkey PRIMARY KEY (asisent_id);

--
-- Name: asistencia_estado asistencia_estado_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_estado
    ADD CONSTRAINT asistencia_estado_pkey PRIMARY KEY (asisest_id);

--
-- Name: asistencia_nino asistencia_nino_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_nino
    ADD CONSTRAINT asistencia_nino_pkey PRIMARY KEY (asisnino_id);

--
-- Name: categoria_nino_grado categoria_nino_grado_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.categoria_nino_grado
    ADD CONSTRAINT categoria_nino_grado_pkey PRIMARY KEY (catninograd_id);

--
-- Name: categoria categorias_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.categoria
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (cat_id);

--
-- Name: colegio_actividad_horario colegio_actividad_horario_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_pkey PRIMARY KEY (colacthor_id);

--
-- Name: colegio_coordinador colegio_coordinador_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_pkey PRIMARY KEY (colcoor_id);

--
-- Name: colegio_coordinador colegio_coordinador_unique; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_unique UNIQUE (col_id, usu_id);

--
-- Name: colegio colegio_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio
    ADD CONSTRAINT colegio_pkey PRIMARY KEY (col_id);

--
-- Name: dia dia_dia_nombre_key; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.dia
    ADD CONSTRAINT dia_dia_nombre_key UNIQUE (dia_nombre);

--
-- Name: dia dia_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.dia
    ADD CONSTRAINT dia_pkey PRIMARY KEY (dia_id);

--
-- Name: encuesta encuesta_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta
    ADD CONSTRAINT encuesta_pkey PRIMARY KEY (encu_id);

--
-- Name: encuesta_pregunta encuesta_pregunta_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_pregunta
    ADD CONSTRAINT encuesta_pregunta_pkey PRIMARY KEY (encupreg_id);

--
-- Name: encuesta_respondida encuesta_respondida_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_respondida
    ADD CONSTRAINT encuesta_respondida_pkey PRIMARY KEY (encurespo_id);

--
-- Name: encuesta_respuesta encuesta_respuesta_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_respuesta
    ADD CONSTRAINT encuesta_respuesta_pkey PRIMARY KEY (encurespu_id);

--
-- Name: encuesta_tipo_respuesta encuesta_tipo_respuesta_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_tipo_respuesta
    ADD CONSTRAINT encuesta_tipo_respuesta_pkey PRIMARY KEY (encutiporesp_id);

--
-- Name: entrenador_asignacion entrenador_asignacion_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_pkey PRIMARY KEY (entasig_id);

--
-- Name: entrenador_auxiliar entrenador_auxiliar_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_pkey PRIMARY KEY (entaux_id);

--
-- Name: entrenador entrenador_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador
    ADD CONSTRAINT entrenador_pkey PRIMARY KEY (ent_id);

--
-- Name: estado estado_est_nombre_key; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.estado
    ADD CONSTRAINT estado_est_nombre_key UNIQUE (est_nombre);

--
-- Name: estado estado_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.estado
    ADD CONSTRAINT estado_pkey PRIMARY KEY (est_id);

--
-- Name: evaluacion_asignacion evaluacion_asignacion_eva_colacthor_unique; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_eva_colacthor_unique UNIQUE (eva_id, colacthor_id);

--
-- Name: evaluacion_asignacion evaluacion_asignacion_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_pkey PRIMARY KEY (evaasig_id);

--
-- Name: evaluacion_intento evaluacion_intento_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_intento
    ADD CONSTRAINT evaluacion_intento_pkey PRIMARY KEY (evaint_id);

--
-- Name: evaluacion_nino_pendiente evaluacion_nino_pendiente_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_pkey PRIMARY KEY (evaninopen_id);

--
-- Name: evaluacion_parametro evaluacion_parametro_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_parametro
    ADD CONSTRAINT evaluacion_parametro_pkey PRIMARY KEY (evaparam_id);

--
-- Name: evaluacion evaluacion_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion
    ADD CONSTRAINT evaluacion_pkey PRIMARY KEY (eva_id);

--
-- Name: evaluacion_tiempo_rangos evaluacion_tiempo_rangos_evaparam_id_key; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_tiempo_rangos
    ADD CONSTRAINT evaluacion_tiempo_rangos_evaparam_id_key UNIQUE (evaparam_id);

--
-- Name: evaluacion_tiempo_rangos evaluacion_tiempo_rangos_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_tiempo_rangos
    ADD CONSTRAINT evaluacion_tiempo_rangos_pkey PRIMARY KEY (evatieran_id);

--
-- Name: evaluacion_tipo_metodo evaluacion_tipo_metodo_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_tipo_metodo
    ADD CONSTRAINT evaluacion_tipo_metodo_pkey PRIMARY KEY (evatipometo_id);

--
-- Name: nino_asignacion nino_asignacion_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_asignacion
    ADD CONSTRAINT nino_asignacion_pkey PRIMARY KEY (ninoasig_id);

--
-- Name: nino nino_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino
    ADD CONSTRAINT nino_pkey PRIMARY KEY (nino_id);

--
-- Name: nino_padre ninopadre_nino_id_padre_id_key; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_padre
    ADD CONSTRAINT ninopadre_nino_id_padre_id_key UNIQUE (nino_id, padre_id);

--
-- Name: nino_padre ninopadre_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_padre
    ADD CONSTRAINT ninopadre_pkey PRIMARY KEY (ninopadre_id);

--
-- Name: padre padre_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.padre
    ADD CONSTRAINT padre_pkey PRIMARY KEY (padre_id);

--
-- Name: rol_permiso rol_permiso_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.rol_permiso
    ADD CONSTRAINT rol_permiso_pkey PRIMARY KEY (rolper_id);

--
-- Name: rol_permiso rol_permiso_rol_id_modulo_accion_key; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.rol_permiso
    ADD CONSTRAINT rol_permiso_rol_id_modulo_accion_key UNIQUE (rol_id, modulo, accion);

--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (rol_id);

--
-- Name: rol rol_rol_nombre_key; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.rol
    ADD CONSTRAINT rol_rol_nombre_key UNIQUE (rol_nombre);

--
-- Name: evaluacion_tiempo_rangos unique_evaparam_id; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_tiempo_rangos
    ADD CONSTRAINT unique_evaparam_id UNIQUE (evaparam_id);

--
-- Name: asistencia_auxiliar uq_auxiliar_fecha_colegio; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_auxiliar
    ADD CONSTRAINT uq_auxiliar_fecha_colegio UNIQUE (usu_id, asisaux_fecha, col_id);

--
-- Name: asistencia_entrenador uq_entrenador_fecha_colegio; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_entrenador
    ADD CONSTRAINT uq_entrenador_fecha_colegio UNIQUE (ent_id, asisent_fecha, col_id);

--
-- Name: asistencia_nino uq_nino_fecha_sesion; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_nino
    ADD CONSTRAINT uq_nino_fecha_sesion UNIQUE (nino_id, colacthor_id, asisnino_fecha);

--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (usu_id);

--
-- Name: usuario_rol usuario_rol_pkey; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.usuario_rol
    ADD CONSTRAINT usuario_rol_pkey PRIMARY KEY (usurol_id);

--
-- Name: usuario usuario_usu_correo_key; Type: CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.usuario
    ADD CONSTRAINT usuario_usu_correo_key UNIQUE (usu_correo);

--
-- Name: idx_asistencia_auxiliar_unique_with_school; Type: INDEX; Schema: archivo; Owner: -
--

CREATE UNIQUE INDEX idx_asistencia_auxiliar_unique_with_school ON archivo.asistencia_auxiliar USING btree (usu_id, asisaux_fecha, col_id);

--
-- Name: idx_asistencia_entrenador_unique_with_school; Type: INDEX; Schema: archivo; Owner: -
--

CREATE UNIQUE INDEX idx_asistencia_entrenador_unique_with_school ON archivo.asistencia_entrenador USING btree (ent_id, asisent_fecha, col_id);

--
-- Name: idx_entrenador_ent_id; Type: INDEX; Schema: archivo; Owner: -
--

CREATE INDEX idx_entrenador_ent_id ON archivo.entrenador USING btree (ent_id);

--
-- Name: idx_padre_padre_id; Type: INDEX; Schema: archivo; Owner: -
--

CREATE INDEX idx_padre_padre_id ON archivo.padre USING btree (padre_id);

--
-- Name: idx_usuario_rol_rol_id; Type: INDEX; Schema: archivo; Owner: -
--

CREATE INDEX idx_usuario_rol_rol_id ON archivo.usuario_rol USING btree (rol_id);

--
-- Name: idx_usuario_rol_usu_id; Type: INDEX; Schema: archivo; Owner: -
--

CREATE INDEX idx_usuario_rol_usu_id ON archivo.usuario_rol USING btree (usu_id);

--
-- Name: actividad actividad_cat_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.actividad
    ADD CONSTRAINT actividad_cat_id_fkey FOREIGN KEY (cat_id) REFERENCES archivo.categoria(cat_id);

--
-- Name: asistencia_auxiliar asistencia_auxiliar_asisest_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_asisest_id_fkey FOREIGN KEY (asisest_id) REFERENCES archivo.asistencia_estado(asisest_id);

--
-- Name: asistencia_auxiliar asistencia_auxiliar_usu_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_usu_id_fkey FOREIGN KEY (usu_id) REFERENCES archivo.usuario(usu_id);

--
-- Name: asistencia_auxiliar asistencia_auxiliar_usu_registrador_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_auxiliar
    ADD CONSTRAINT asistencia_auxiliar_usu_registrador_fkey FOREIGN KEY (usu_registrador) REFERENCES archivo.usuario(usu_id);

--
-- Name: asistencia_entrenador asistencia_entrenador_asisest_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_asisest_id_fkey FOREIGN KEY (asisest_id) REFERENCES archivo.asistencia_estado(asisest_id);

--
-- Name: asistencia_entrenador asistencia_entrenador_ent_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_ent_id_fkey FOREIGN KEY (ent_id) REFERENCES archivo.entrenador(ent_id);

--
-- Name: asistencia_entrenador asistencia_entrenador_usu_registrador_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_entrenador
    ADD CONSTRAINT asistencia_entrenador_usu_registrador_fkey FOREIGN KEY (usu_registrador) REFERENCES archivo.usuario(usu_id);

--
-- Name: asistencia_nino asistencia_nino_asisest_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_nino
    ADD CONSTRAINT asistencia_nino_asisest_id_fkey FOREIGN KEY (asisest_id) REFERENCES archivo.asistencia_estado(asisest_id);

--
-- Name: asistencia_nino asistencia_nino_colacthor_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_nino
    ADD CONSTRAINT asistencia_nino_colacthor_id_fkey FOREIGN KEY (colacthor_id) REFERENCES archivo.colegio_actividad_horario(colacthor_id);

--
-- Name: asistencia_nino asistencia_nino_nino_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_nino
    ADD CONSTRAINT asistencia_nino_nino_id_fkey FOREIGN KEY (nino_id) REFERENCES archivo.nino(nino_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: asistencia_nino asistencia_nino_usu_registrador_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_nino
    ADD CONSTRAINT asistencia_nino_usu_registrador_fkey FOREIGN KEY (usu_registrador) REFERENCES archivo.usuario(usu_id);

--
-- Name: colegio_actividad_horario colegio_actividad_horario_act_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_act_id_fkey FOREIGN KEY (act_id) REFERENCES archivo.actividad(act_id);

--
-- Name: colegio_actividad_horario colegio_actividad_horario_col_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_col_id_fkey FOREIGN KEY (col_id) REFERENCES archivo.colegio(col_id);

--
-- Name: colegio_actividad_horario colegio_actividad_horario_dia_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_dia_id_fkey FOREIGN KEY (dia_id) REFERENCES archivo.dia(dia_id);

--
-- Name: colegio_actividad_horario colegio_actividad_horario_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_actividad_horario
    ADD CONSTRAINT colegio_actividad_horario_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: colegio_coordinador colegio_coordinador_col_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_col_id_fkey FOREIGN KEY (col_id) REFERENCES archivo.colegio(col_id);

--
-- Name: colegio_coordinador colegio_coordinador_usu_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.colegio_coordinador
    ADD CONSTRAINT colegio_coordinador_usu_id_fkey FOREIGN KEY (usu_id) REFERENCES archivo.usuario(usu_id);

--
-- Name: encuesta encuesta_encu_creador_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta
    ADD CONSTRAINT encuesta_encu_creador_fkey FOREIGN KEY (encu_creador) REFERENCES archivo.usuario(usu_id);

--
-- Name: encuesta encuesta_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta
    ADD CONSTRAINT encuesta_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: encuesta_pregunta encuesta_pregunta_encu_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_pregunta
    ADD CONSTRAINT encuesta_pregunta_encu_id_fkey FOREIGN KEY (encu_id) REFERENCES archivo.encuesta(encu_id) ON DELETE CASCADE;

--
-- Name: encuesta_pregunta encuesta_pregunta_encutiporesp_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_pregunta
    ADD CONSTRAINT encuesta_pregunta_encutiporesp_id_fkey FOREIGN KEY (encutiporesp_id) REFERENCES archivo.encuesta_tipo_respuesta(encutiporesp_id);

--
-- Name: encuesta_respondida encuesta_respondida_encu_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_respondida
    ADD CONSTRAINT encuesta_respondida_encu_id_fkey FOREIGN KEY (encu_id) REFERENCES archivo.encuesta(encu_id) ON DELETE CASCADE;

--
-- Name: encuesta_respondida encuesta_respondida_padre_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_respondida
    ADD CONSTRAINT encuesta_respondida_padre_id_fkey FOREIGN KEY (padre_id) REFERENCES archivo.padre(padre_id);

--
-- Name: encuesta_respuesta encuesta_respuesta_encupreg_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_respuesta
    ADD CONSTRAINT encuesta_respuesta_encupreg_id_fkey FOREIGN KEY (encupreg_id) REFERENCES archivo.encuesta_pregunta(encupreg_id) ON DELETE CASCADE;

--
-- Name: encuesta_respuesta encuesta_respuesta_encurespo_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.encuesta_respuesta
    ADD CONSTRAINT encuesta_respuesta_encurespo_id_fkey FOREIGN KEY (encurespo_id) REFERENCES archivo.encuesta_respondida(encurespo_id) ON DELETE CASCADE;

--
-- Name: entrenador_asignacion entrenador_asignacion_colacthor_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_colacthor_id_fkey FOREIGN KEY (colacthor_id) REFERENCES archivo.colegio_actividad_horario(colacthor_id);

--
-- Name: entrenador_asignacion entrenador_asignacion_ent_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_ent_id_fkey FOREIGN KEY (ent_id) REFERENCES archivo.entrenador(ent_id);

--
-- Name: entrenador_asignacion entrenador_asignacion_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_asignacion
    ADD CONSTRAINT entrenador_asignacion_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: entrenador_auxiliar entrenador_auxiliar_ent_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_ent_id_fkey FOREIGN KEY (ent_id) REFERENCES archivo.entrenador(ent_id);

--
-- Name: entrenador_auxiliar entrenador_auxiliar_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: entrenador_auxiliar entrenador_auxiliar_rol_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES archivo.rol(rol_id);

--
-- Name: entrenador_auxiliar entrenador_auxiliar_usu_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador_auxiliar
    ADD CONSTRAINT entrenador_auxiliar_usu_id_fkey FOREIGN KEY (usu_id) REFERENCES archivo.usuario(usu_id);

--
-- Name: entrenador entrenador_ent_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador
    ADD CONSTRAINT entrenador_ent_id_fkey FOREIGN KEY (ent_id) REFERENCES archivo.usuario(usu_id);

--
-- Name: entrenador entrenador_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador
    ADD CONSTRAINT entrenador_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: evaluacion_asignacion evaluacion_asignacion_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: evaluacion_asignacion evaluacion_asignacion_eva_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_asignacion_eva_id_fkey FOREIGN KEY (eva_id) REFERENCES archivo.evaluacion(eva_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: evaluacion_asignacion evaluacion_disciplina_colacthor_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_asignacion
    ADD CONSTRAINT evaluacion_disciplina_colacthor_id_fkey FOREIGN KEY (colacthor_id) REFERENCES archivo.colegio_actividad_horario(colacthor_id);

--
-- Name: evaluacion evaluacion_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion
    ADD CONSTRAINT evaluacion_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: evaluacion evaluacion_eva_creador_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion
    ADD CONSTRAINT evaluacion_eva_creador_fkey FOREIGN KEY (eva_creador) REFERENCES archivo.usuario(usu_id);

--
-- Name: evaluacion_intento evaluacion_intento_evaninopen_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_intento
    ADD CONSTRAINT evaluacion_intento_evaninopen_id_fkey FOREIGN KEY (evaninopen_id) REFERENCES archivo.evaluacion_nino_pendiente(evaninopen_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: evaluacion_intento evaluacion_intento_evaparam_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_intento
    ADD CONSTRAINT evaluacion_intento_evaparam_id_fkey FOREIGN KEY (evaparam_id) REFERENCES archivo.evaluacion_parametro(evaparam_id);

--
-- Name: evaluacion_nino_pendiente evaluacion_nino_pendiente_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: evaluacion_nino_pendiente evaluacion_nino_pendiente_eva_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_eva_id_fkey FOREIGN KEY (eva_id) REFERENCES archivo.evaluacion(eva_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: evaluacion_nino_pendiente evaluacion_nino_pendiente_ninoasig_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_ninoasig_id_fkey FOREIGN KEY (ninoasig_id) REFERENCES archivo.nino_asignacion(ninoasig_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: evaluacion_nino_pendiente evaluacion_nino_pendiente_usu_id_registrador_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_nino_pendiente
    ADD CONSTRAINT evaluacion_nino_pendiente_usu_id_registrador_fkey FOREIGN KEY (usu_id_registrador) REFERENCES archivo.usuario(usu_id);

--
-- Name: evaluacion_parametro evaluacion_parametro_eva_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_parametro
    ADD CONSTRAINT evaluacion_parametro_eva_id_fkey FOREIGN KEY (eva_id) REFERENCES archivo.evaluacion(eva_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: evaluacion_parametro evaluacion_parametro_evatipometo_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_parametro
    ADD CONSTRAINT evaluacion_parametro_evatipometo_id_fkey FOREIGN KEY (evatipometo_id) REFERENCES archivo.evaluacion_tipo_metodo(evatipometo_id);

--
-- Name: evaluacion_tiempo_rangos evaluacion_tiempo_rangos_evaparam_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.evaluacion_tiempo_rangos
    ADD CONSTRAINT evaluacion_tiempo_rangos_evaparam_id_fkey FOREIGN KEY (evaparam_id) REFERENCES archivo.evaluacion_parametro(evaparam_id) ON DELETE CASCADE;

--
-- Name: asistencia_auxiliar fk_asistencia_auxiliar_colegio; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_auxiliar
    ADD CONSTRAINT fk_asistencia_auxiliar_colegio FOREIGN KEY (col_id) REFERENCES archivo.colegio(col_id);

--
-- Name: asistencia_entrenador fk_asistencia_entrenador_colegio; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.asistencia_entrenador
    ADD CONSTRAINT fk_asistencia_entrenador_colegio FOREIGN KEY (col_id) REFERENCES archivo.colegio(col_id);

--
-- Name: entrenador fk_entrenador_usuario; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.entrenador
    ADD CONSTRAINT fk_entrenador_usuario FOREIGN KEY (ent_id) REFERENCES archivo.usuario(usu_id) ON DELETE CASCADE;

--
-- Name: nino_asignacion nino_asignacion_colacthor_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_asignacion
    ADD CONSTRAINT nino_asignacion_colacthor_id_fkey FOREIGN KEY (colacthor_id) REFERENCES archivo.colegio_actividad_horario(colacthor_id);

--
-- Name: nino_asignacion nino_asignacion_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_asignacion
    ADD CONSTRAINT nino_asignacion_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: nino_asignacion nino_asignacion_nino_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_asignacion
    ADD CONSTRAINT nino_asignacion_nino_id_fkey FOREIGN KEY (nino_id) REFERENCES archivo.nino(nino_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: nino nino_catninograd_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino
    ADD CONSTRAINT nino_catninograd_id_fkey FOREIGN KEY (catninograd_id) REFERENCES archivo.categoria_nino_grado(catninograd_id);

--
-- Name: nino nino_col_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino
    ADD CONSTRAINT nino_col_id_fkey FOREIGN KEY (col_id) REFERENCES archivo.colegio(col_id);

--
-- Name: nino nino_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino
    ADD CONSTRAINT nino_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: nino_padre nino_padre_nino_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_padre
    ADD CONSTRAINT nino_padre_nino_id_fkey FOREIGN KEY (nino_id) REFERENCES archivo.nino(nino_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: nino_padre ninopadre_padre_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.nino_padre
    ADD CONSTRAINT ninopadre_padre_id_fkey FOREIGN KEY (padre_id) REFERENCES archivo.padre(padre_id);

--
-- Name: padre padre_usu_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.padre
    ADD CONSTRAINT padre_usu_id_fkey FOREIGN KEY (usu_id) REFERENCES archivo.usuario(usu_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
-- Name: rol_permiso rol_permiso_rol_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.rol_permiso
    ADD CONSTRAINT rol_permiso_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES archivo.rol(rol_id) ON DELETE CASCADE;

--
-- Name: usuario usuario_est_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.usuario
    ADD CONSTRAINT usuario_est_id_fkey FOREIGN KEY (est_id) REFERENCES archivo.estado(est_id);

--
-- Name: usuario_rol usuario_rol_rol_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.usuario_rol
    ADD CONSTRAINT usuario_rol_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES archivo.rol(rol_id);

--
-- Name: usuario_rol usuario_rol_usu_id_fkey; Type: FK CONSTRAINT; Schema: archivo; Owner: -
--

ALTER TABLE ONLY archivo.usuario_rol
    ADD CONSTRAINT usuario_rol_usu_id_fkey FOREIGN KEY (usu_id) REFERENCES archivo.usuario(usu_id) ON UPDATE CASCADE ON DELETE CASCADE;

--
--

COMMENT ON SCHEMA archivo IS
    'Copia congelada de la plataforma vieja (respaldo 2026-10-01). Solo lectura, para Reportes > Data anterior. 0013.';

-- ---------------------------------------------------------------------
-- Cerradura
-- ---------------------------------------------------------------------

DO $$
DECLARE
    t record;
BEGIN
    FOR t IN SELECT c.relname FROM pg_class c
             WHERE c.relnamespace = 'archivo'::regnamespace AND c.relkind = 'r'
    LOOP
        EXECUTE format('ALTER TABLE archivo.%I ENABLE ROW LEVEL SECURITY, FORCE ROW LEVEL SECURITY', t.relname);
    END LOOP;
END
$$;

REVOKE ALL ON SCHEMA archivo FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES    IN SCHEMA archivo FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA archivo FROM PUBLIC, anon, authenticated;

GRANT USAGE  ON SCHEMA archivo               TO service_role;
GRANT SELECT ON ALL TABLES IN SCHEMA archivo TO service_role;

-- ---------------------------------------------------------------------
-- Se comprueba a sí misma
-- ---------------------------------------------------------------------

DO $$
DECLARE
    n_tablas    integer;
    n_sin_rls   integer;
    n_politicas integer;
    n_abiertas  integer;
    n_triggers  integer;
    n_funciones integer;
    n_sensibles integer;
BEGIN
    SELECT count(*) INTO n_tablas FROM pg_class
     WHERE relnamespace = 'archivo'::regnamespace AND relkind = 'r';
    SELECT count(*) INTO n_sin_rls FROM pg_class
     WHERE relnamespace = 'archivo'::regnamespace AND relkind = 'r'
       AND NOT (relrowsecurity AND relforcerowsecurity);
    SELECT count(*) INTO n_politicas FROM pg_policies WHERE schemaname = 'archivo';
    SELECT count(*) INTO n_abiertas FROM pg_class c
     WHERE c.relnamespace = 'archivo'::regnamespace AND c.relkind = 'r'
       AND (has_table_privilege('anon', c.oid, 'SELECT')
         OR has_table_privilege('authenticated', c.oid, 'SELECT'));
    SELECT count(*) INTO n_triggers FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
     WHERE c.relnamespace = 'archivo'::regnamespace AND NOT t.tgisinternal;
    SELECT count(*) INTO n_funciones FROM pg_proc WHERE pronamespace = 'archivo'::regnamespace;
    SELECT count(*) INTO n_sensibles FROM information_schema.columns
     WHERE table_schema = 'archivo'
       AND column_name IN ('usu_contrasena', 'usu_foto', 'nino_info_salud', 'nino_otra_info',
                           'nino_cedula', 'nino_foto', 'col_rep_foto');

    IF n_tablas <> 35 OR n_sin_rls <> 0 OR n_politicas <> 0 OR n_abiertas <> 0
       OR n_triggers <> 0 OR n_funciones <> 0 OR n_sensibles <> 0 THEN
        RAISE EXCEPTION 'archivo mal: tablas=% sin_rls=% politicas=% abiertas=% triggers=% funciones=% sensibles=%',
            n_tablas, n_sin_rls, n_politicas, n_abiertas, n_triggers, n_funciones, n_sensibles;
    END IF;
    RAISE NOTICE 'archivo OK: 35 tablas, RLS forzado, sin políticas, cerrado a anon y authenticated.';
END
$$;

COMMIT;
