-- =====================================================================
-- PVCAR — 0021_disciplinas_horarios.sql
-- Disciplinas v2: una disciplina es un grupo con varios horarios.
-- Decidido con el cliente el 2026-10-05/06 (docs/disciplinas-v2.md).
--
-- Requiere 0001-0020. Va en PVCAR_Dev y en PVCAR. Todo en una
-- transacción. Idempotente: si ya se aplicó, no hace nada.
--
-- ---------------------------------------------------------------------
-- Qué cambia
--
-- 1. Tabla nueva `disciplina_horario`: un día por fila (día, hora de
--    inicio, hora de fin). Cada día puede tener su propia hora.
-- 2. `colegio_actividad_horario` pasa a ser la DISCIPLINA entera y
--    conserva su id: niños, entrenadores, evaluaciones, asistencias e
--    inscripciones siguen apuntando al mismo `colacthor_id`. Pierde
--    `dia_id` y las horas, que se mudan a la tabla hija.
-- 3. Las filas de hoy que son "el mismo grupo en otro día" —mismo
--    colegio, actividad, estado y franja, distinto día— se juntan en una
--    sola disciplina (la de id menor). Lo que colgaba de las otras se
--    pasa a ella sin duplicar. En dev son 3 pares; prod está vacía.
-- 4. `inscripcion_config.inscfg_max_disciplinas` (por defecto 2): el
--    tope por niño. Solo lo aplica el formulario público; desde la
--    plataforma el personal puede pasarlo (cliente, 2026-10-06).
-- 5. `disciplina_horario_texto(id)`: "Lun y Mié 15:00–16:00" o
--    "Lun 15:00–16:00 · Mié 16:00–17:00". La usan los listados.
-- 6. Auxiliar con varios titulares (Fase 9 §1b): unicidad parcial
--    (usu_id, ent_id) entre las filas activas de `entrenador_auxiliar`.
--
-- El esquema `archivo` (Data anterior) no se toca.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. La tabla de horarios
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.disciplina_horario (
    dishor_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colacthor_id        integer  NOT NULL
        REFERENCES public.colegio_actividad_horario (colacthor_id) ON DELETE CASCADE,
    dia_id              smallint NOT NULL REFERENCES public.dia (dia_id),
    dishor_hora_inicio  time     NOT NULL,
    dishor_hora_fin     time     NOT NULL,
    CONSTRAINT ck_dishor_horas CHECK (dishor_hora_fin > dishor_hora_inicio),
    CONSTRAINT uq_dishor_dia   UNIQUE (colacthor_id, dia_id)
);

CREATE INDEX IF NOT EXISTS idx_dishor_dia ON public.disciplina_horario (dia_id);

COMMENT ON TABLE public.disciplina_horario IS
    'Los días de una disciplina: uno por fila, cada uno con su hora. Una disciplina no repite día.';

ALTER TABLE public.disciplina_horario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disciplina_horario FORCE  ROW LEVEL SECURITY;
REVOKE ALL ON public.disciplina_horario FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.disciplina_horario TO service_role;

-- ---------------------------------------------------------------------
-- 2 y 3. Mudar los horarios y juntar los grupos partidos por día
-- ---------------------------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name   = 'colegio_actividad_horario'
          AND column_name  = 'dia_id'
    ) THEN
        RAISE NOTICE '0021 ya aplicada: no se mudan horarios';
        RETURN;
    END IF;

    -- Qué fila sobrevive por cada grupo.
    CREATE TEMP TABLE fusion ON COMMIT DROP AS
    SELECT colacthor_id AS viejo,
           min(colacthor_id) OVER (
               PARTITION BY col_id, act_id, est_id, colacthor_hora_inicio, colacthor_hora_fin
           ) AS nuevo
    FROM public.colegio_actividad_horario;

    -- Si dentro de un grupo se repite el día, no es el mismo grupo:
    -- no se junta nada de ese grupo (cada fila queda como disciplina).
    UPDATE fusion f SET nuevo = f.viejo
    WHERE f.nuevo IN (
        SELECT f2.nuevo
        FROM fusion f2
        JOIN public.colegio_actividad_horario d ON d.colacthor_id = f2.viejo
        GROUP BY f2.nuevo
        HAVING count(*) <> count(DISTINCT d.dia_id)
    );

    -- Filas sin día u horas (no debería haber): no se pueden mudar.
    IF EXISTS (
        SELECT 1 FROM public.colegio_actividad_horario
        WHERE dia_id IS NULL OR colacthor_hora_inicio IS NULL OR colacthor_hora_fin IS NULL
           OR colacthor_hora_fin <= colacthor_hora_inicio
    ) THEN
        RAISE EXCEPTION 'Hay disciplinas sin día u horas válidas: revisar antes de migrar';
    END IF;

    INSERT INTO public.disciplina_horario (colacthor_id, dia_id, dishor_hora_inicio, dishor_hora_fin)
    SELECT f.nuevo, d.dia_id, d.colacthor_hora_inicio, d.colacthor_hora_fin
    FROM public.colegio_actividad_horario d
    JOIN fusion f ON f.viejo = d.colacthor_id;

    -- Inscripciones de niños. Si ya está activo en la que sobrevive, la
    -- copia sobra: se borran sus evaluaciones pendientes y ella.
    DELETE FROM public.evaluacion_nino_pendiente p
    USING public.nino_asignacion na, fusion f
    WHERE p.ninoasig_id = na.ninoasig_id
      AND f.viejo = na.colacthor_id AND f.viejo <> f.nuevo
      AND EXISTS (SELECT 1 FROM public.nino_asignacion k
                  WHERE k.nino_id = na.nino_id AND k.colacthor_id = f.nuevo
                    AND (k.est_id = na.est_id OR na.est_id <> 1));
    DELETE FROM public.nino_asignacion na
    USING fusion f
    WHERE f.viejo = na.colacthor_id AND f.viejo <> f.nuevo
      AND EXISTS (SELECT 1 FROM public.nino_asignacion k
                  WHERE k.nino_id = na.nino_id AND k.colacthor_id = f.nuevo
                    AND (k.est_id = na.est_id OR na.est_id <> 1));
    UPDATE public.nino_asignacion na SET colacthor_id = f.nuevo
    FROM fusion f WHERE f.viejo = na.colacthor_id AND f.viejo <> f.nuevo;

    -- Entrenadores: la abierta duplicada se cierra; el resto se pasa.
    UPDATE public.entrenador_asignacion ea
       SET entasig_fecha_fin = CURRENT_DATE, est_id = 2
      FROM fusion f
     WHERE f.viejo = ea.colacthor_id AND f.viejo <> f.nuevo
       AND ea.entasig_fecha_fin IS NULL
       AND EXISTS (SELECT 1 FROM public.entrenador_asignacion k
                   WHERE k.ent_id = ea.ent_id AND k.colacthor_id = f.nuevo
                     AND k.entasig_fecha_fin IS NULL);
    UPDATE public.entrenador_asignacion ea SET colacthor_id = f.nuevo
    FROM fusion f WHERE f.viejo = ea.colacthor_id AND f.viejo <> f.nuevo;

    -- Evaluaciones vinculadas: una vez por disciplina.
    DELETE FROM public.evaluacion_asignacion ev
    USING fusion f
    WHERE f.viejo = ev.colacthor_id AND f.viejo <> f.nuevo
      AND EXISTS (SELECT 1 FROM public.evaluacion_asignacion k
                  WHERE k.eva_id = ev.eva_id AND k.colacthor_id = f.nuevo);
    UPDATE public.evaluacion_asignacion ev SET colacthor_id = f.nuevo
    FROM fusion f WHERE f.viejo = ev.colacthor_id AND f.viejo <> f.nuevo;

    -- Asistencias: son por fecha, y fechas de días distintos no chocan.
    UPDATE public.asistencia_nino a SET colacthor_id = f.nuevo
    FROM fusion f WHERE f.viejo = a.colacthor_id AND f.viejo <> f.nuevo;

    -- Lo que pidió cada inscripción en línea (ids sin FK).
    UPDATE public.inscripcion_nino i
       SET insnino_disciplinas = (
           SELECT array_agg(DISTINCT COALESCE(f.nuevo, x) ORDER BY COALESCE(f.nuevo, x))
           FROM unnest(i.insnino_disciplinas) AS x
           LEFT JOIN fusion f ON f.viejo = x
       )
     WHERE i.insnino_disciplinas && (SELECT array_agg(viejo) FROM fusion WHERE viejo <> nuevo);

    DELETE FROM public.colegio_actividad_horario d
    USING fusion f WHERE f.viejo = d.colacthor_id AND f.viejo <> f.nuevo;
END $$;

DROP INDEX IF EXISTS public.colacthor_unica_idx;
DROP INDEX IF EXISTS public.idx_cah_dia_id;
ALTER TABLE public.colegio_actividad_horario
    DROP CONSTRAINT IF EXISTS colegio_actividad_horario_dia_id_fkey,
    DROP COLUMN IF EXISTS dia_id,
    DROP COLUMN IF EXISTS colacthor_hora_inicio,
    DROP COLUMN IF EXISTS colacthor_hora_fin;

COMMENT ON TABLE public.colegio_actividad_horario IS
    'La disciplina: colegio + actividad. Sus días y horas están en disciplina_horario. El nombre se queda por compatibilidad.';

-- ---------------------------------------------------------------------
-- 4. Tope de disciplinas por niño en el formulario público
-- ---------------------------------------------------------------------

ALTER TABLE public.inscripcion_config
    ADD COLUMN IF NOT EXISTS inscfg_max_disciplinas smallint NOT NULL DEFAULT 2;
ALTER TABLE public.inscripcion_config
    DROP CONSTRAINT IF EXISTS ck_inscfg_max_disciplinas;
ALTER TABLE public.inscripcion_config
    ADD CONSTRAINT ck_inscfg_max_disciplinas CHECK (inscfg_max_disciplinas BETWEEN 1 AND 10);

COMMENT ON COLUMN public.inscripcion_config.inscfg_max_disciplinas IS
    'Máximo de disciplinas por niño en el formulario público. Desde la plataforma no hay tope.';

-- ---------------------------------------------------------------------
-- 5. El horario como texto
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.disciplina_horario_texto(p_colacthor_id integer)
    RETURNS text
    LANGUAGE sql
    STABLE
    SET search_path TO 'public'
AS $$
    WITH franjas AS (
        SELECT h.dishor_hora_inicio AS ini,
               h.dishor_hora_fin    AS fin,
               array_agg(left(d.dia_nombre, 3) ORDER BY h.dia_id) AS dias,
               min(h.dia_id) AS primero
        FROM disciplina_horario h
        JOIN dia d ON d.dia_id = h.dia_id
        WHERE h.colacthor_id = p_colacthor_id
        GROUP BY h.dishor_hora_inicio, h.dishor_hora_fin
    )
    SELECT string_agg(
               CASE WHEN cardinality(dias) = 1 THEN dias[1]
                    ELSE array_to_string(dias[1:cardinality(dias) - 1], ', ')
                         || ' y ' || dias[cardinality(dias)]
               END
               || ' ' || to_char(ini, 'HH24:MI') || '–' || to_char(fin, 'HH24:MI'),
               ' · ' ORDER BY primero)
    FROM franjas;
$$;

REVOKE ALL ON FUNCTION public.disciplina_horario_texto(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.disciplina_horario_texto(integer) TO service_role;

-- ---------------------------------------------------------------------
-- 6. Un auxiliar con varios titulares
-- ---------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS entrenador_auxiliar_activo_unico_idx
    ON public.entrenador_auxiliar (usu_id, ent_id)
    WHERE est_id = 1;

COMMENT ON INDEX public.entrenador_auxiliar_activo_unico_idx IS
    'Un auxiliar puede respaldar a varios titulares, pero a cada uno una sola vez a la vez.';

-- ---------------------------------------------------------------------
-- Comprobaciones
-- ---------------------------------------------------------------------

DO $$
DECLARE
    sin_horario int;
    columnas    int;
BEGIN
    SELECT count(*) INTO sin_horario
    FROM public.colegio_actividad_horario d
    WHERE NOT EXISTS (SELECT 1 FROM public.disciplina_horario h WHERE h.colacthor_id = d.colacthor_id);

    SELECT count(*) INTO columnas
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'colegio_actividad_horario'
      AND column_name IN ('dia_id', 'colacthor_hora_inicio', 'colacthor_hora_fin');

    IF sin_horario > 0 THEN RAISE EXCEPTION '% disciplinas quedaron sin horario', sin_horario; END IF;
    IF columnas > 0 THEN RAISE EXCEPTION 'Quedan columnas de horario en la tabla madre'; END IF;
    IF has_table_privilege('anon', 'public.disciplina_horario', 'SELECT')
       OR has_table_privilege('authenticated', 'public.disciplina_horario', 'SELECT') THEN
        RAISE EXCEPTION 'disciplina_horario quedó abierta a anon o authenticated';
    END IF;
END $$;

COMMIT;
